### ISSUE TITLE
Entities with @Indexed cause Mongock instantiation failure

### ISSUE THREAD

**Issue by smnnn** [cloudyrock/mongock#132]
Hello

We are trying out mongock in a Spring Boot project. The creation of the SpringBootMongock bean seems to fail when an entity with the ```@Indexed``` annotation exists. When removing the ```@Indexed``` annotation from the (unrelated) entity, everything works as expected. Note that the indices have been correctly created by the time the SpringBootMongock bean instantiation fails.

full annotation name: org.springframework.data.mongodb.core.index.Indexed

Our setup: 
```
@Configuration
public class MongockConfig {

    private static final String CHANGE_LOGS_SCAN_PACKAGE = "my.company.servicename.persistence.upgrade";

    private final MongoTemplate mongoTemplate;
    private final ApplicationContext applicationContext;

    @Autowired
    public MongockConfig(MongoTemplate mongoTemplate, ApplicationContext applicationContext) {
        this.mongoTemplate = mongoTemplate;
        this.applicationContext = applicationContext;
    }

    @Bean
    public Mongock mongock() {
        return new SpringBootMongockBuilder(mongoTemplate, CHANGE_LOGS_SCAN_PACKAGE)
                .setApplicationContext(applicationContext)
                .setLockQuickConfig()
                .build();
    }
}
```

```
@ChangeLog
public class MongoChangeLog {

    private static final String CHANGE_SET_001 = "change-set-001.yaml";

    @ChangeSet(order = "001", id = "cefc0a3d-1905-46d2-8635-e7a468c40fec", author = "author")
    public void changeSet001(AircraftDao aircraftDao) {
        UpgradeUtils.createAircraftEntities(getClass().getResourceAsStream(CHANGE_SET_001))
                .forEach(aircraftDao::save);
    }
}
```

Entity causing issues
```
@Data
@Builder
@Document
public class Attachment {

    @Id
    private String id;
    @Indexed(name="expire-index", expireAfter="P2D")
    private LocalDateTime createdAt;
    ...
}
```

```
11:37:46.578 - ERROR - org.springframework.boot.SpringApplication - Application run failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongock' defined in class path resource [my/company/service/persistence/config/MongockConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.Mongock]: Factory method 'mongock' threw exception; nested exception is java.lang.NullPointerException
 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)
 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
 	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$240.000000008C98DDC0.getObject(Unknown Source)
 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
 	at my.company.servicename.application.GeodataServiceApplication.main(GeodataServiceApplication.java:13)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
 Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.Mongock]: Factory method 'mongock' threw exception; nested exception is java.lang.NullPointerException
 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
 	... 28 common frames omitted
 Caused by: java.lang.NullPointerException: null
 	at com.github.cloudyrock.mongock.decorator.impl.MongoTemplateDecoratorImpl.execute(MongoTemplateDecoratorImpl.java:154)
 	at org.springframework.data.mongodb.core.DefaultIndexOperations.execute(DefaultIndexOperations.java:214)
 	at org.springframework.data.mongodb.core.DefaultIndexOperations.ensureIndex(DefaultIndexOperations.java:121)
 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:158)
 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:148)
 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:130)
 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.<init>(MongoPersistentEntityIndexCreator.java:95)
 	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.<init>(MongoPersistentEntityIndexCreator.java:72)
 	at org.springframework.data.mongodb.core.MongoTemplate.<init>(MongoTemplate.java:275)
 	at com.github.cloudyrock.mongock.decorator.impl.MongoTemplateDecoratorImpl.<init>(MongoTemplateDecoratorImpl.java:65)
 	at com.github.cloudyrock.mongock.SpringMongockBuilderBase.createMongoTemplateProxy(SpringMongockBuilderBase.java:115)
 	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.createMongockInstance(SpringBootMongockBuilder.java:71)
 	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.createMongockInstance(SpringBootMongockBuilder.java:11)
 	at com.github.cloudyrock.mongock.MongockBuilderBase.build(MongockBuilderBase.java:197)
 	at my.company.servicename.persistence.config.MongockConfig.mongock(MongockConfig.java:30)
 	at my.company.servicename.persistence.config.MongockConfig$$EnhancerBySpringCGLIB$$e83328b9.CGLIB$mongock$0(<generated>)
 	at my.company.servicename.persistence.config.MongockConfig$$EnhancerBySpringCGLIB$$e83328b9$$FastClassBySpringCGLIB$$a6a217f8.invoke(<generated>)
 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
 	at my.company.servicename.persistence.config.MongockConfig$$EnhancerBySpringCGLIB$$e83328b9.mongock(<generated>)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
 	... 29 common frames omitted
```

**Comment by dieppa** [comment]
Thanks, we'll have a look as soon as possible(my expectation is today). Could you provide version of springboot, spring data and Mongock, please?

Thanks @smnnn

**Comment by smnnn** [comment]
Thanks for the quick response. We are using:
Spring Boot/Spring Data/Spring Mongo: 2.2.4.RELEASE
mongock-spring: 3.2.3

Same issue using the version 2.2.3.RELEASE of Spring
Also no changes with or without the mongock-spring exclusion of mongo-java-driver

**Comment by dieppa** [comment]
Thanks, no worries, we were already able to reproduce. It's a tricky one, which have several solutions, but we need to evaluate pros and cons. I am confidence you can expect to have it fixed at the end of today, but I cannot commit. In the worse case, by Thursday evening.

Cheers

**Comment by dieppa** [comment]
Hello @smnnn, 
I said we were able to release a version today, but I need to say sorry because that won't be possible.

I think we will be able to have it done by tomorrow, but then we need to perform some tests, so it will be probably Monday.

Regards

**Comment by dieppa** [comment]
Hi @smnnn ,

please give a try to version 3.2.4. Let me know if it works for you, so I can close this issue

Note: Don't forget to use MongoTemplate in your changelog. NO MongoClient. ;)

**Comment by smnnn** [comment]
@dieppa 
We gave 3.2.4 a try, works great. Thank you!
