### ISSUE TITLE
ChangeSet.runAlways not working for mongock version 3.2.3

### ISSUE THREAD

**Issue by radhe-soni** [cloudyrock/mongock#133]
* Spring-Boot version - 2.2.3.RELEASE
* Spring management plugin version - 1.0.9.RELEASE
* Mongo db version - 4.2.3
## My Configuration -
@ChangeSet(id = "alwaysRunMigrations", order = "011", author = "my_service", systemVersion = "4", runAlways = true)

Error -
`Caused by: com.mongodb.MongoWriteException: E11000 duplicate key error collection: myDB.mongockChangeLog index: author_1_changeId_1 dup key: { author: "my_service", changeId: "alwaysRunMigrations" }
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1055) ~[mongodb-driver-3.11.2.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:498) ~[mongodb-driver-3.11.2.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:482) ~[mongodb-driver-3.11.2.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:476) ~[mongodb-driver-3.11.2.jar:?]
	at com.github.cloudyrock.mongock.ChangeEntryMongoRepository.save(ChangeEntryMongoRepository.java:26) ~[mongock-core-3.2.3.jar:?]
	at com.github.cloudyrock.mongock.Mongock.executeIfNewOrRunAlways(Mongock.java:153) ~[mongock-core-3.2.3.jar:?]`

**Comment by dieppa** [comment]
fixed at the end of today

**Comment by dieppa** [comment]
quick question, you just started using Mongock or you upgraded from 2.X.

Because it only makes sense if you are upgrading from 2.x. That's why we haven't made it officla yet. We need to document the process. 

So, if, as said, you upgrading, please keep 2.x until Monday, when I believe I can give you the exact steps you need to execute(very easy), or we even add them to Mongock so you don't need to do anything.

If you are just running Mongock 3.X from scratch, please let me know, because that means the issue is something else.

Cheers

**Comment by radhe-soni** [comment]
1. I was running mongock 2.0.2 version on windows.
2. I changed my os to ubuntu, everything got refreshed right from .gradle directory to JVM(oraclejdk to openjdk). 
3. Now the system gave me some cglib-asm directory error. 
4. At this point I decided to update mongock version.

**Comment by dieppa** [comment]
Cool, I know exactly what error you are facing. And I can commit to provide you a solution by Monday. You may even don't need to do anything, just use the last version we'll release on Monday, but in the worse case scenario, you might be required to do some very easy process.

In version 3.x we move from cglib(before we were using proxies) so you don't need to worry about that anymore.

So, please use 3.0.5.BETA until Monday ;)

**Comment by dieppa** [comment]
Hello @radhe-soni ,

we have a new release which make this easy for you. Don't need to do anything, just update the maven dependency to 3.2.4.

Please let me know how it goes.
Thanks
