### ISSUE TITLE
AbstractMongoEventListener BeforeConvertEvent not getting called

### ISSUE THREAD

**Issue by zambardus** [cloudyrock/mongock#138]
Hi, I am shifting from Mongobee to Mongock because of mongobee issue#87

I am using following version for my spring boot application:     
`compile('com.github.cloudyrock.mongock:mongock-spring:3.2.4')`

I had created a sequence generator in my application whose purpose was to save the _id as a numerical value which was done through onBeforeConvert() method event extended from AbstractMongoEventListener abstract class defined in mongodb.core.mapping.event package. So I used to bulk add static data through changesets using MongoTemplate with just passing the content of the data without caring for setting the _id as it was handled by sequence generator. 
 ```
@ChangeSet(author = "zambardus",id="pin_code_seeder",order="001")
    public void populatePinCode(MongoTemplate mongoTemplate)
    {  
         List<PinCodeModel> pinCodes = fetchPinCodes();// which reads pincodes from a json file and convert to PinCodeModel object
         mongoTemplate.insertAll(pinCodes);
    }
```
This was working fine with Mongobee but when I shifted to Mongock, the onBeforeConvert() method doesn't get called and hence I get the below error as it tries to save by default value of 0 for id: 
```
Caused by: com.mongodb.MongoBulkWriteException: Bulk write operation error on server localhost:27017. Write errors: [BulkWriteError{index=0, code=11000, message='E11000 duplicate key error collection: db.pinCode index: _id_ dup key: { _id: 0 }', details={}}]. 
	at com.mongodb.connection.BulkWriteBatchCombiner.getError(BulkWriteBatchCombiner.java:173) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.connection.BulkWriteBatchCombiner.throwOnError(BulkWriteBatchCombiner.java:202) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.connection.BulkWriteBatchCombiner.getResult(BulkWriteBatchCombiner.java:143) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.operation.BulkWriteBatch.getResult(BulkWriteBatch.java:227) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:282) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:72) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:205) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:196) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:501) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:196) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:71) ~[mongodb-driver-core-3.11.2.jar:na]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:206) ~[mongodb-driver-3.11.2.jar:na]
	at com.mongodb.client.internal.MongoCollectionImpl.executeInsertMany(MongoCollectionImpl.java:524) ~[mongodb-driver-3.11.2.jar:na]
	at com.mongodb.client.internal.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:508) ~[mongodb-driver-3.11.2.jar:na]
	at com.mongodb.client.internal.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:503) ~[mongodb-driver-3.11.2.jar:na]
	at com.github.cloudyrock.mongock.decorator.MongoCollectionDecorator.lambda$insertMany$17(MongoCollectionDecorator.java:168) ~[mongock-core-3.2.4.jar:na]
	at com.github.cloudyrock.mongock.decorator.util.MethodInvokerImpl.invoke(MethodInvokerImpl.java:24) ~[mongock-core-3.2.4.jar:na]
	at com.github.cloudyrock.mongock.decorator.MongoCollectionDecorator.insertMany(MongoCollectionDecorator.java:168) ~[mongock-core-3.2.4.jar:na]
	at com.github.cloudyrock.mongock.decorator.MongoCollectionDecorator.lambda$insertMany$17(MongoCollectionDecorator.java:168) ~[mongock-core-3.2.4.jar:na]
	at com.github.cloudyrock.mongock.decorator.util.MethodInvokerImpl.invoke(MethodInvokerImpl.java:24) ~[mongock-core-3.2.4.jar:na]
	at com.github.cloudyrock.mongock.decorator.MongoCollectionDecorator.insertMany(MongoCollectionDecorator.java:168) ~[mongock-core-3.2.4.jar:na]
	at com.github.cloudyrock.mongock.decorator.MongoCollectionDecorator.lambda$insertMany$17(MongoCollectionDecorator.java:168) ~[mongock-core-3.2.4.jar:na]
	at com.github.cloudyrock.mongock.decorator.util.MethodInvokerImpl.invoke(MethodInvokerImpl.java:24) ~[mongock-core-3.2.4.jar:na]
	at com.github.cloudyrock.mongock.decorator.MongoCollectionDecorator.insertMany(MongoCollectionDecorator.java:168) ~[mongock-core-3.2.4.jar:na]
	at org.springframework.data.mongodb.core.MongoTemplate.lambda$insertDocumentList$17(MongoTemplate.java:1526) ~[spring-data-mongodb-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:585) ~[spring-data-mongodb-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	... 38 common frames omitted
```

**Comment by dieppa** [comment]
Hello @zambardus,

we'll be looking at this today and will come back to you either this evening or tomorrow morning(UK time).

Cheers

**Comment by dieppa** [comment]
meanwhile can you provide all the information you can, like spring version, mongoDB, etc.

Cheers

**Comment by dieppa** [comment]
and also the way you are building Mongock object, that's quite important

**Comment by zambardus** [comment]
Springboot version: 2.2.2.RELEASE
Mongo DB version: 4.2.3

Mongock object initiation:

```
@Configuration
public class MongockConfig {

    @Value("${spring.data.mongodb.database}")
    private String database;

    @Value("${spring.data.mongodb.uri}")
    private String mongoUri;

    @Bean
    public SpringBootMongock mongock(ApplicationContext springContext) {
        MongoClient mongoClient = new MongoClient(new MongoClientURI(mongoUri));
        return new SpringBootMongockBuilder(mongoClient, database, "com.changelog.path")
                .setApplicationContext(springContext)
                .setLockQuickConfig()
                .build();
    }
```

**Comment by dieppa** [comment]
Ok, can you try by using MongoTemplate instead of mongoClient, as you can see below?

`
@Bean
    public SpringBootMongock mongock(ApplicationContext springContext, MongoTemplatemongotemplate) {
        return new SpringBootMongockBuilder(mongotemplate,ClientChangeLog.class.getPackage().getName())
                .setApplicationContext(springContext)
                . setLockQuickConfig()
                .build();
    }
`

**Comment by zambardus** [comment]
You are correct in pointing out to declare mongoTemplate, as I read it [here](https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/index/MongoMappingEventPublisher.html) 

> Declare MongoTemplate inside an ApplicationContext to enable the publishing of all persistence events such as AfterLoadEvent, AfterSaveEvent, etc.

But it didn't help as I am still getting the same error. Also, it takes 127.0.0.1:27017 as the mongo url since I didn't mention mongo client's url

**Comment by dieppa** [comment]
Hi @zambardus ,

I am missing something here. You are saying that MongoTemplate is taking 127.0.0.1:27017?
If that is right, the problem is that you are no configuring MongoTemplate correctly. You probably need to add your mongoDB configuration properties, like url and port, in your spring property file and then, you MongoTemplate will take and then you can inject it to Mongock.

**Comment by zambardus** [comment]
Hey, that has been configured. But still the issue persists.

**Comment by dieppa** [comment]
can you send me an email with the code for the Mongock generation and that new error trace as antonio@cloudyrock.io, please?

**Comment by dieppa** [comment]
Hi @zambardus,

I have been digging into this. It's not a bug. The method onBeforeConvert on AbstractMongoEventListener is called when using a Repository, no when using MongoTemplate.

As you can read in Mongock's documentation, you are free to use Repositories in your changelogs by just declaring the bean and add it in the Change set method signature. However, currently repository actions are not covered by the lock. This is planned in our roadmap as one of the priorities, but not yet implemented. If you are running this in a microservice or clustered environment, I don't recommend hitting the databases without a lock.

**Comment by zambardus** [comment]
Working fine with MongoRepository. Thanks for the support and advice for using locks with repository.
