### ISSUE TITLE
document does not contain key clustertime

### ISSUE THREAD

**Issue by MatellioBharatGupta** [cloudyrock/mongock#203]
Getting this error, when i am trying to connect to Mongo Atlas. Please help.

**Comment by dieppa** [comment]
Hello @MatellioBharatGupta ,

please can you provide a bit more information, such as:
- error stack trace
- Versions: Mongock, MongoDB, Spring

and anything it could be useful

I will try to have a look tomorrow

**Comment by MatellioBharatGupta** [comment]
Versions: 
Mongock : 3.2.4
MongoDB : Version 4.2.8(Atlas)
SpringBoot : 2.0.5.RELEAS

Building mongock : 
  @Bean
    public SpringMongock springMongock(MongoTemplate mongoTemplate, Environment springEnvironment) {
        return new SpringMongockBuilder(mongoTemplate, "changeLogScanPackage")
            .setSpringEnvironment(springEnvironment)
            .setLockQuickConfig()
      .build();
    }

Yes, it is giving in changelog . I have so many change logs in my project. 
    @ChangeSet(order = "01", author = "initiator", id = "01-addAuthorities")
    public void addAuthorities(MongoTemplate mongoTemplate) {
        Role adminAuthority = new Role();
        adminAuthority.setId(AuthoritiesConstants.ADMIN);
        adminAuthority.setName(AuthoritiesConstants.ADMIN_NAME);
        mongoTemplate.save(adminAuthority);


A few days ago all was working fine. But on this last Friday, We faced this error. Then we moved from Mongobee to Mongock. Still we are facing the same error.
If i comment the mogock bean then all becomes ok, but i need the mongock into my project. 

logs:
Caused by: org.bson.BsonInvalidOperationException: Document does not contain key clusterTime
        at org.bson.BsonDocument.throwIfKeyAbsent(BsonDocument.java:859) ~[mongo-java-driver-3.6.4.jar:?]
        at org.bson.BsonDocument.getTimestamp(BsonDocument.java:257) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.ClusterClock.greaterOf(ClusterClock.java:40) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.ClusterClock.advance(ClusterClock.java:31) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.ClusterClockAdvancingSessionContext.advanceClusterTime(ClusterClockAdvancingSessionContext.java:71) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.InternalStreamConnection.updateSessionContext(InternalStreamConnection.java:511) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:292) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:98) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:441) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:80) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:189) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:264) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:126) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:118) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:226) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:217) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:120) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.ListIndexesOperation$1.call(ListIndexesOperation.java:143) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.ListIndexesOperation$1.call(ListIndexesOperation.java:138) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:471) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:415) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.ListIndexesOperation.execute(ListIndexesOperation.java:138) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.operation.ListIndexesOperation.execute(ListIndexesOperation.java:69) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.Mongo$3.execute(Mongo.java:826) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.MongoIterableImpl.execute(MongoIterableImpl.java:130) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.MongoIterableImpl.iterator(MongoIterableImpl.java:77) ~[mongo-java-driver-3.6.4.jar:?]
        at com.mongodb.MongoIterableImpl.iterator(MongoIterableImpl.java:32) ~[mongo-java-driver-3.6.4.jar:?]

**Comment by dieppa** [comment]
Hello, I see a couple of things here, that not necessary are related to your issue, but it would be nice to discard first:

1) You say you're using MongoDB 4.x and [this doc](https://docs.atlas.mongodb.com/driver-connection/#java-driver-example) stands you should be using the driver version 3.8 or greater. However, I can see in your logs you're using 3.6.4

2) Is there any reason you are not using the last Mongock version? For version 3.x, the last one it's 3.3.2. However, we recommend you to use the version 4, although it's in beta. 4.1.0.beta. In this version you can use the last MongoDB driver version(mongodb-driver-sync:4.0.2) or the last Spring data for mongo(spring-data-mongodb:3.0.0.RELEASE). We haven't release the official documentation yet, but you can an example [here](https://github.com/cloudyrock/mongock/issues/195), in my first comment.

3) Either if you opt for most updated Mongock version 3.x or the latest one(4.1.0.beta), you should be using MongockTemplare, instead MongoTemplate. It's just a wrapper, you won't notice a difference.

Please, update this and try again. Let me know how it goes and we take a proper look.

**Comment by MatellioBharatGupta** [comment]
Hello @dieppa , 
If i use 
  <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.8.2</version>
        </dependency>

then i got 
java.lang.ClassNotFoundException: org.springframework.data.mongodb.core.ExecutableMapReduceOperation$MapReduceWithMapFunction

then i put 

 <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-mongodb</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>


then i got 

[ERROR] /home/cgt_jpr_lin_bharat/Documents/projects//-gateway/src/main/java/com//config/InheritanceAwareMongoRepositoryFactory.java:[76,24] cannot access org.springframework.data.repository.query.QueryMethodEvaluationContextProvider
[ERROR]   class file for org.springframework.data.repository.query.QueryMethodEvaluationContextProvider not found
[ERROR] /home/cgt_jpr_lin_bharat/Documents/projects//-gateway/src/main/java/com//config/InheritanceAwareMongoRepositoryFactory.java:[79,94] incompatible types: org.springframework.data.repository.query.EvaluationContextProvider cannot be converted to org.springframework.data.repository.query.QueryMethodEvaluationContextProvider
[ERROR] /home/cgt_jpr_lin_bharat/Documents/projects//-gateway/src/main/java/com//config/InheritanceAwarePartTreeMongoQuery.java:[18,9] constructor PartTreeMongoQuery in class org.springframework.data.mongodb.repository.query.PartTreeMongoQuery cannot be applied to given types;
[ERROR]   required: org.springframework.data.mongodb.repository.query.MongoQueryMethod,org.springframework.data.mongodb.core.MongoOperations,org.springframework.expression.spel.standard.SpelExpressionParser,org.springframework.data.repository.query.QueryMethodEvaluationContextProvider
[ERROR]   found: org.springframework.data.mongodb.repository.query.MongoQueryMethod,org.springframework.data.mongodb.core.MongoOperations
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR] 



If i upgrade my InheritanceAwareMongoRepositoryFactory class according to above error, i need to change my repository and some queries also that i can not afford to do in project.

Please help me with some other way.

**Comment by dieppa** [comment]
Hello  @MatellioBharatGupta ,


I am not sure I understand what you did, but I understand your MongoDB version is 4.x, so you should be using Java driver >3.8. More information [here](https://docs.mongodb.com/drivers/java)

I also understand you are using Spring data 2.x. So for that you need to use Mongock driver **mongodb-springdata-v2-driver** which uses Mongo Java driver 3.x.

Please follow this instructions(It's basically what I provided in the link above, but with the right artifacts for Spring data 2). Also make sure you provide the right MongoD and Spring Data as per step (3). As Example we use 3.11.0 and 2.2.4.RELASE, but you should be fine changing the minor and patch versions

Anyway I provide the basic steps you should follow:
1.  Add Mongock bom to your pom:
```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.cloudyrock.mongock</groupId>
                <artifactId>mongock-bom</artifactId>
                <version>4.1.1.BETA</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

2. provide Mongock runner and Mongock Driver dependencies
```xml

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v2-driver</artifactId>
        </dependency>
```

3. As these Mongock dependencies don't bring MongoDB driver nor Spring data dependencies, to avoid transitive dependencies, you need to import them. Serve as example:

```xml

    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongo-java-driver</artifactId>
      <version>3.11.0</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-mongodb</artifactId>
      <version>2.2.4.RELEASE</version>
      <scope>provided</scope>
    </dependency>

```

4. Add you changeLog package path to your property file. Please note that change-logs-scan-package is an array, so you can now provide several packages. Although everything you could set up before with the builder(and still now if you choose the builder approach) can be configured in properties file, if you find any issue or difficulty let us know. However, the minimal configuration require is at least a valid changeLog package path. Mongock provide default values for the the other properties. Worth mentioning the lock which is now enabled by default.
```yaml
spring:
  mongock:
    change-logs-scan-package:
      - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.initializer
```

5. Annotate your SpringBootApplication with @EnableMongock
```java
@EnableMongock
@SpringBootApplication
public class App {

  public static void main(String[] args) {
    new SpringApplicationBuilder().sources(App.class).run(args);
  }
}
```

**Comment by mmichalko** [comment]
I had the same issue, fixed it by upgrading spring boot version from 2.0.1 to 2.2.7 (which updated the mongo driver to 3.11) and upgrading mongock from 2.0.2 to 3.3.2.
