### ISSUE TITLE
Mongock with writeConcern=0;

### ISSUE THREAD

**Issue by savvadem** [cloudyrock/mongock#209]
Hello.

We met next problem on our load testing.
We tried to set writeConcern=0 in uri connection string, to check perfomance of our app, but could not start it, because mongock failed to start our app.

```
Caused by: java.lang.UnsupportedOperationException: Cannot get information about an unacknowledged update
	at com.mongodb.client.result.UpdateResult$UnacknowledgedUpdateResult.getUnacknowledgedWriteException(UpdateResult.java:202) ~[mongodb-driver-core-3.11.2.jar!/:na]
	at com.mongodb.client.result.UpdateResult$UnacknowledgedUpdateResult.getModifiedCount(UpdateResult.java:192) ~[mongodb-driver-core-3.11.2.jar!/:na]
	at com.github.cloudyrock.mongock.LockMongoRepository.insertUpdate(LockMongoRepository.java:92) ~[mongock-core-3.2.4.jar!/:na]
	at com.github.cloudyrock.mongock.LockMongoRepository.insertUpdate(LockMongoRepository.java:36) ~[mongock-core-3.2.4.jar!/:na]
      at com.github.cloudyrock.mongock.LockChecker.acquireLock(LockChecker.java:99) ~[mongock-core-3.2.4.jar!/:na]
	at com.github.cloudyrock.mongock.LockChecker.acquireLockDefault(LockChecker.java:90) ~[mongock-core-3.2.4.jar!/:na]
	at com.github.cloudyrock.mongock.Mongock.execute(Mongock.java:93) ~[mongock-core-3.2.4.jar!/:na]
	at com.github.cloudyrock.mongock.SpringBootMongock.run(SpringBootMongock.java:24) ~[mongock-spring-3.2.4.jar!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775) [spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
```

Looks like you should set writeConcern explicitly, or its just I shouldn't use w=0?

**Comment by dieppa** [comment]
Hello @savvadem ,

I would explain you the technical reasons behind, but you are probably not interested. So in summary, Mongock requires write concern to manage the lock. 

We will be providing some new test features as part of version 4.x. One of them will allow to disable the lock in tests. Although currently version 4.1.2.BETA is out(RC probably next week), this lock-disabling feature is not provided yet.

For version 3.X, the one you seem to be using, we won't be providing this feature though.

**Comment by savvadem** [comment]
Yes, i mean that you could set writeConcern(WriteConcern#ACKNOWLEDGED) explicitly for your particular operation (checking the lock), ignoring the one specified by user in connection string. Or it's bad practice?

**Comment by dieppa** [comment]
Yes, if you specify the write concern in the operation, it overrides the one set in the URI.
Doesn't seem to be a bad practice.

I'll let you know by tomorrow when this could be fixed. As you probably understand, as you are the only one facing this and the environment affected is testing, it is not that priority. However, we expect to have it done in the next days.

Thanks

**Comment by savvadem** [comment]
No problem, just posted FYI, that with w=0 in connection string it wont work. 

Thanks for reply.

**Comment by dieppa** [comment]
**added to roadmap**
