### ISSUE TITLE
How to import Mongock 4 properly to Spring Boot Application?

### ISSUE THREAD

**Issue by jfenuk** [cloudyrock/mongock#213]
I am trying to integrate Mongock 4 with my Spring Boot application (2.2.8.RELEASE)
What I did:
- added mongock-bom

``` 
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.cloudyrock.mongock</groupId>
                <artifactId>mongock-bom</artifactId>
                <version>4.1.2.BETA</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
</dependencies>
</dependencyManagement>
```

- added

```
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
        </dependency>
```

- property file updated:
```
spring:
  mongock:
    change-logs-scan-package:
      - com.acme.project-name.changelog
```

- @EnableMongock added:
```
@SpringBootApplication
@EnableMongock
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
```

- ChangeLog file with ChangeSet added:

```
import com.github.cloudyrock.mongock.ChangeLog;
import com.github.cloudyrock.mongock.ChangeSet;
import org.springframework.data.mongodb.core.MongoTemplate;

@ChangeLog
public class DatabaseChangeLog {

    @ChangeSet(id = "unique_id", author = "yevhenii", order = "001")
    public void changeset(MongoTemplate template) {

        System.out.println(template.getDb().getName());
    }
}
```

When I tried to run the application via `mvn spring-boot:run` I got the following error:
```

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4ChangeEntryRepository.save(MongoSync4ChangeEntryRepository.java:55)

The following method did not exist:

    'com.mongodb.client.result.InsertOneResult com.mongodb.client.MongoCollection.insertOne(java.lang.Object)'

The method's class, com.mongodb.client.MongoCollection, is available from the following locations:

    jar:file:/home/user/.m2/repository/org/mongodb/mongo-java-driver/3.12.6/mongo-java-driver-3.12.6.jar!/com/mongodb/client/MongoCollection.class

It was loaded from the following location:

    file:/home/user/.m2/repository/org/mongodb/mongo-java-driver/3.12.6/mongo-java-driver-3.12.6.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.mongodb.client.MongoCollection
```

- when I changed `pom.xml`
```
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v2-driver</artifactId>
        </dependency>
```
I got a new error:
```
Caused by: io.changock.migration.api.exception.ChangockException: 

MONGOCK DRIVER HAS NOT BEEN IMPORTED
====================================
        SOLUTION: You need to import one of these artifacts
        - 'mongodb-springdata-v3-driver' for springdata 3
        - 'mongodb-springdata-v2-driver' for springdata 2


        at com.github.cloudyrock.spring.v5.MongockCoreContextSelector.selectImports(MongockCoreContextSelector.java:18) ~[mongock-spring-v5-4.1.2.BETA.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:580) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        ... 20 more

```

So, could you please clarify what exactly I did in the wrong way? and how to get working Spring Boot application 2.2.8 with Mongock 4 integration?

**Comment by dieppa** [comment]
Hi @jfenuk ,

first sorry because we haven't released official documentation yet. We'll try to have it available next week as we're having a lot of users asking the same question.

Meanwhile, please see these resources:

- [issue answering this](https://github.com/cloudyrock/mongock/issues/203)
- [sample project](https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-4/mongock-spring-v5/mongock-spring5-springdata3-it)
- [stackoverflow related question](https://stackoverflow.com/questions/62908825/an-attempt-was-made-to-call-a-method-that-does-not-exist-com-github-cloudyrock-m/62916185#62916185)

**Comment by dieppa** [comment]
Take into account that, if you are using spring data 3(mongoDB java driver 4) you need to import mongock spring 3 driver.
On the other hand, if you are using spring data 2(mongoDB java driver 3) you need to import mongock spring 2 driver.

In both cases, and I think this is the reason of your issue, you need to import required transitive dependencies(Java MongoDb driver and MongoDB spring data)

**Comment by dieppa** [comment]
Is this resolved?

**Comment by jfenuk** [comment]
@dieppa , yes, thank you.
