### ISSUE TITLE
NoClassDefFoundError: javassist/bytecode/ClassFile

### ISSUE THREAD

**Issue by joelroyer** [cloudyrock/mongock#218]
I'm trying to run changelogs but I've got this error:
```
java.lang.NoClassDefFoundError: javassist/bytecode/ClassFile
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	at org.reflections.Reflections.scan(Reflections.java:243)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at org.reflections.Reflections.<init>(Reflections.java:169)
	at io.changock.runner.core.ChangeLogService.lambda$fetchChangeLogClassesSorted$1(ChangeLogService.java:95)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.changock.runner.core.ChangeLogService.fetchChangeLogClassesSorted(ChangeLogService.java:97)
	at io.changock.runner.core.ChangeLogService.fetchChangeLogs(ChangeLogService.java:85)
	at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:44)
	at io.changock.runner.spring.v5.ChangockSpringBuilderBase$ChangockSpringApplicationRunner.run(ChangockSpringBuilderBase.java:107)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.acme.Application.main(Application.java:37)
Caused by: java.lang.ClassNotFoundException: javassist.bytecode.ClassFile
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 25 common frames omitted
```

Using those dependencies:
- Spring Boot 2.3.1 in reactive mode with Netty Server
- Mongock 4.1.4.BETA

The POM :
```xml
<dependencyManagement>
	<dependency>
		<groupId>com.github.cloudyrock.mongock</groupId>
		<artifactId>mongock-bom</artifactId>
		<version>4.1.4.BETA</version>
		<type>pom</type>
		<scope>import</scope>
	</dependency>
</dependencyManagement>
<dependencies>
	<dependency>
		<groupId>com.github.cloudyrock.mongock</groupId>
		<artifactId>mongock-spring-v5</artifactId>
	</dependency>
	<dependency>
		<groupId>com.github.cloudyrock.mongock</groupId>
		<artifactId>mongodb-springdata-v3-driver</artifactId>
	</dependency>
</dependencies>
```

The property is set in application.yaml :
```yaml
spring:
  mongock:
    change-logs-scan-package:
      - com.acme.changelogs
```

@EnableMongock added on the main class and the changelog class is:
```java
@ChangeLog
public class DatabaseChangelog {
	@ChangeSet(order = "001", id = "001-update-session-model", author = "johndoe")
	public void updateSessionModel(MongoTemplate mongoTemplate) throws IOException {
		System.out.println("Test");
	}
}
```

**Comment by dieppa** [comment]
Hello @joelroyer ,

first, we haven't provided reactive support yet for Mongock. Take into account that you cannot use MongoTemplate directly in your ChangeSet methods, you must use MongockTemplate. So in order to support Mongo reactive with spring, we would need to provide MongockReactiveTemplate.

Said that, I see that you are using non-reactive approach by using MongoTemplate. We haven't tested yet, but the error you are getting is something different. Not found javassist. That doesn't make much sense as that transitive dependency is brought by library Reflections. Unless you are taking it out from your pom explicitly somehow.  

However, regardless the log, I believe it's related to some mess up with templates, I'd suggest to make sure there is nothing messing up the templates.

Try to collect a bit more useful information and we'll try to help. Otherwise, as currently Mongock doesn't support reactive and we are really full of work, we cant't go deep into that right now

**Comment by joelroyer** [comment]
Thanks for your response. Indeed, we use a non-reactive approach.

I've tried with MongockTemplate in place of MongoTemplate but error still occurs.

We have the same code on another service, and it works well.

**Comment by dieppa** [comment]
Well, keep using MongockTemplate.

Very weird. As said, that class is brought by |Reflections" library. can you provide the dependency tree by executing `mvn dependency:tree`

You can send it to me by [email](mailto://antonio@cloudyrock.io) if you prefer.

**Comment by joelroyer** [comment]
`mvn dependency:tree` done and found a mistake on third-party dependency.
You can close this issue.

**Comment by dieppa** [comment]
glad you found it, @joelroyer.

Can you tell me what was the issue so I can address it faster next time? :)

**Comment by joelroyer** [comment]
We use Powermock for some tests and the developer who set it up followed this ticket:
https://stackoverflow.com/questions/31189086/powermock-and-java-8-issue-interfacemethodrefinfo-cannot-be-cast-to-methodrefin

In this ticket, you can see that javassist is excluded from powermock junit4 module dependencies and added manually in another version with scope "test".

But the developer didn't see the warning above the answer. I removed scope and it runs!

**Comment by dieppa** [comment]
great, thanks!
