### ISSUE TITLE
Mongock reexecutes ChangeSet after upgrading Mongock on Spring boot

### ISSUE THREAD

**Issue by abhishekshah2905** [cloudyrock/mongock#221]
- Spring-Boot version: 2.3.1.RELEASE
- Mongo db version: 4.2.3
- Old Mongock version: 3.2.3
- New Mongock Version: 4.0.0.alpha

Earlier, I was using the old mongo version where most of the ChangeSets are already migrated. Now, I upgraded the mongock version to user the latest Spring and Mongo Sync driver. However, It looks like already migrated ChangeSets are again executing and throwing below exception on Mongo Atlas.

I saw the similar issue on repo. It was on the same situation which I do have
Link: [Mongock reexecutes ChangeSet on every run](https://github.com/cloudyrock/mongock/issues/107)

**Exception:** 
Caused by: io.changock.migration.api.exception.ChangockException: Error in method[InitialSetupMigration.addAuthorities] : E11000 duplicate key error collection: eeviction.mongockChangeLog index: author_1_changeId_1 dup key: { author: "initiator", changeId: "01-addAuthorities" }
	at io.changock.runner.core.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:153)
	at io.changock.runner.core.MigrationExecutor.executeMigration(MigrationExecutor.java:71)
	at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:44)
	at com.github.cloudyrock.mongock.SpringBootMongock.execute(SpringBootMongock.java:25)
	at com.github.cloudyrock.mongock.SpringBootMongock.run(SpringBootMongock.java:21)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	... 12 common frames omitted
Caused by: com.mongodb.MongoWriteException: E11000 duplicate key error collection: eeviction.mongockChangeLog index: author_1_changeId_1 dup key: { author: "initiator", changeId: "01-addAuthorities" }
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1015)
	at com.mongodb.client.internal.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:469)
	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:452)
	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:446)
	at io.changock.driver.mongo.syncv4.core.repository.MongoChangeEntryRepository.save(MongoChangeEntryRepository.java:53)
	at io.changock.runner.core.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:103)
	at io.changock.runner.core.MigrationExecutor.executeMigration(MigrationExecutor.java:69)
	... 16 common frames omitted

**Comment by dieppa** [comment]
Hello, I don't think Mongock reexecutes your changeSets again. However it processes(and track) them every time. This means that  in every Mongock's execution, it iterates over all the changeSets and check if they have been executed or not. If they have been already executed, in version 4.0.0.alpha, the one you're using, it will try to track that changeSet was processed, but not executed(IGNORED).

in the last version, 4.1.5.BETA, which I suggest you to use, it won't track ignored changeSets, unless you explicitly indicates so by specifying `track-ignored=true`. See the [unreleased documentation](https://www.mongock.io/standalone#building-time-runner) for more information.

**Anyway, the issue seems to be with the keys. I believe that was fixed, so by using the last version 4.1.5.BETA, it should work fine. Please check that with last version and let us know. If still remains, we'll fix it.**

Regards

**Comment by abhishekshah2905** [comment]
@dieppa 

Thanks for the quick response. Is this version of library released on maven? It seems to not loading on classpath after **4.1.5.BETA**

**Comment by dieppa** [comment]
Yes, it's in maven. Please check the "quick start" section in the documentation I provided earlier ;)

**Comment by abhishekshah2905** [comment]
@dieppa 

Thanks. I'll go over with it and keep you posted here for the same which you requested. Thanks

**Comment by abhishekshah2905** [comment]
@dieppa 

It is working as expected after using the **4.1.5.BETA** version of library
