### ISSUE TITLE
Transactions can not be disabled

### ISSUE THREAD

**Issue by olivierboudet** [cloudyrock/mongock#240]
Hello,

I am using mongock with a Spring Boot 2.3 application.
This is artifact versions I am using : 
```
|    +--- com.github.cloudyrock.mongock:mongock-bom:4.1.8
|    |    +--- com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:4.1.8 (c)
|    |    +--- com.github.cloudyrock.mongock:mongock-spring-v5:4.1.8 (c)
|    |    +--- com.github.cloudyrock.changock:changock-driver-core:1.1.1 (c)
|    |    +--- com.github.cloudyrock.mongock:mongock-api:4.1.8 (c)
|    |    +--- com.github.cloudyrock.mongock:mongodb-sync-v4-driver:4.1.8 (c)
|    |    +--- com.github.cloudyrock.changock:changock-spring-v5-runner:1.1.1 (c)
|    |    +--- com.github.cloudyrock.changock:changock-driver-api:1.1.1 (c)
|    |    +--- com.github.cloudyrock.changock:changock-api:1.1.1 (c)
|    |    +--- com.github.cloudyrock.changock:changock-runner-core:1.1.1 (c)
|    |    \--- com.github.cloudyrock.changock:changock-spring-runner-util:1.1.1 (c)
```

I try to ignore transaction in some tests. So I try to set the `transaction-enabled` property to false: 

```
spring
  mongock:
    transaction-enabled: false
```

At startup, I have this error : 

```
Failed to bind properties under 'spring.mongock' to com.github.cloudyrock.spring.v5.MongockConfiguration$$EnhancerBySpringCGLIB$$eec52c35:

    Property: spring.mongock.transaction-enabled
    Value: false
    Origin: class path resource [application.yml]:27:26
    Reason: No setter found for property: transaction-enabled

```

Moreover, transactions *must* be disabled when we have a TransactionManager in the context but some changelogs alter collections (ie. createIndex, dropIndex, etc)

**Comment by dieppa** [comment]
Sorry for the delay in the response. I thought this was one I already replied.

We'll take a look and let you know

**Comment by dieppa** [comment]
Actually sorry, which version you are using. If you take a loom to the [documentation](https://www.mongock.io), it's not `spring.mongock` anymore, just `mongock`

**Comment by olivierboudet** [comment]
As stated in my first comment, I am using version mongock-bom:4.1.8, do you need someting else ?

It is not working netiher with `mongock.transaction-enabled: false`. In this case, the error encountered is the following : 

`
Caused by: com.mongodb.MongoClientException: Sessions are not supported by the MongoDB cluster to which this client is connected
	at com.mongodb.client.internal.MongoClientImpl.startSession(MongoClientImpl.java:128)
	at org.springframework.data.mongodb.core.SimpleMongoClientDatabaseFactory.getSession(SimpleMongoClientDatabaseFactory.java:84)
	at org.springframework.data.mongodb.MongoTransactionManager.newResourceHolder(MongoTransactionManager.java:350)
	at org.springframework.data.mongodb.MongoTransactionManager.doBegin(MongoTransactionManager.java:139)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.SpringDataMongo3Driver.getTxStatus(SpringDataMongo3Driver.java:122)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.SpringDataMongo3Driver.executeInTransaction(SpringDataMongo3Driver.java:105)
	at io.changock.runner.core.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:72)
	at io.changock.runner.core.MigrationExecutor.executeMigration(MigrationExecutor.java:63)
	at io.changock.runner.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:44)
	... 7 common frames omitted
`

**Comment by dieppa** [comment]
ok, I will try to reproduce the error. But can you upgrade to the last Mongock version(4.1.15) and send me the error trace?
Thanks

**Comment by olivierboudet** [comment]
ok, I have test it with following dependencies 

```
|    +--- com.github.cloudyrock.mongock:mongock-bom:4.1.8 -> 4.1.15
|    |    +--- com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:4.1.15 (c)
|    |    +--- com.github.cloudyrock.mongock:mongock-spring-v5:4.1.15 (c)
|    |    +--- com.github.cloudyrock.changock:changock-driver-core:1.1.4 (c)
|    |    +--- com.github.cloudyrock.mongock:mongock-api:4.1.15 (c)
|    |    +--- com.github.cloudyrock.mongock:mongodb-sync-v4-driver:4.1.15 (c)
|    |    +--- com.github.cloudyrock.changock:changock-spring-v5-runner:1.1.4 (c)
|    |    +--- com.github.cloudyrock.changock:changock-driver-api:1.1.4 (c)
|    |    +--- com.github.cloudyrock.changock:changock-api:1.1.4 (c)
|    |    +--- com.github.cloudyrock.changock:changock-runner-core:1.1.4 (c)
|    |    \--- com.github.cloudyrock.changock:changock-spring-runner-util:1.1.4 (c)
```

When I set the property `mongock.transaction-enable: false` or `mongock.transaction-enabled: false` (in doubt, I tried both), I have this error : 
```

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.cooperl.csuite.datawarehouse.DatawarehouseApplication.main(DatawarehouseApplication.java:26)
Caused by: io.changock.migration.api.exception.ChangockException: com.mongodb.MongoClientException: Sessions are not supported by the MongoDB cluster to which this client is connected
	at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:56)
	at io.changock.runner.spring.v5.ChangockSpringBuilderBase$ChangockSpringApplicationRunner.run(ChangockSpringBuilderBase.java:107)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	... 5 common frames omitted
Caused by: com.mongodb.MongoClientException: Sessions are not supported by the MongoDB cluster to which this client is connected
	at com.mongodb.client.internal.MongoClientImpl.startSession(MongoClientImpl.java:128)
	at org.springframework.data.mongodb.core.SimpleMongoClientDatabaseFactory.getSession(SimpleMongoClientDatabaseFactory.java:84)
	at org.springframework.data.mongodb.MongoTransactionManager.newResourceHolder(MongoTransactionManager.java:350)
	at org.springframework.data.mongodb.MongoTransactionManager.doBegin(MongoTransactionManager.java:139)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.SpringDataMongo3Driver.getTxStatus(SpringDataMongo3Driver.java:122)
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.SpringDataMongo3Driver.executeInTransaction(SpringDataMongo3Driver.java:105)
	at io.changock.runner.core.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:72)
	at io.changock.runner.core.MigrationExecutor.executeMigration(MigrationExecutor.java:63)
	at io.changock.runner.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:44)
	... 7 common frames omitted
```

**Comment by dieppa** [comment]
OK, this is really useful. Will take a look and let you know as soon as possible.

**Comment by dieppa** [comment]
Hello @olivierboudet , we have been too busy.
We'll try to take a look and tell you something today. No promises though.

**Comment by dieppa** [comment]
Hello @olivierboudet ,

we have identified a bug in the configuration, which somehow produces your issue, so we'll be releasing a new bug-fix today. We'll let you you know.

However, I say somehow because that would only affect if you are also injecting the transactionManager, because the condition to enable transactions in Mongock is that the property `mongock.transaction-enabled` is set to `true` AND there is a `MongoTransactionManager` injected in the Spring context. With this new release it will work anyway as this "and condition" won't be satisfied, but it may be worthy for you to check this.

**Comment by olivierboudet** [comment]
Hello @dieppa ,

Thanks a lot. And yes, I have a MongoTransactionManager because I use transactions in my application. But mongo 4.2 does not support creating indexes and collections in transactions, so I need to disable transaction in mongock changelog (because I am creating collections and indexes in changelogs)

**Comment by dieppa** [comment]
cool, thanks. That makes sense now.

So I will let you know when it's released, but unless something terrible happens, you'll have it today

**Comment by dieppa** [comment]
Hello @olivierboudet ,

this issue should be resolved in the new released version 4.1.16. Please give it a try and let me know.

Thanks

**Comment by olivierboudet** [comment]
Hello @dieppa,

Thanks but I always have the issue.

**./gradlew dependencies**
```
|    +--- com.github.cloudyrock.mongock:mongock-bom:4.1.16
|    |    +--- com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:4.1.16 (c)
|    |    +--- com.github.cloudyrock.mongock:mongock-spring-v5:4.1.16 (c)
|    |    +--- com.github.cloudyrock.changock:changock-driver-core:1.1.5 (c)
|    |    +--- com.github.cloudyrock.mongock:mongock-api:4.1.16 (c)
|    |    +--- com.github.cloudyrock.mongock:mongodb-sync-v4-driver:4.1.16 (c)
|    |    +--- com.github.cloudyrock.changock:changock-spring-v5-runner:1.1.5 (c)
|    |    +--- com.github.cloudyrock.changock:changock-api:1.1.5 (c)
|    |    +--- com.github.cloudyrock.changock:changock-runner-core:1.1.5 (c)
|    |    +--- com.github.cloudyrock.changock:changock-driver-api:1.1.5 (c)
|    |    \--- com.github.cloudyrock.changock:changock-spring-runner-util:1.1.5 (c)
```

**In application.yaml :** 
```
mongock:
  change-logs-scan-package: com.cooperl.csuite.datawarehouse.changelogs
  transaction-enabled: false
```

**Error**

```

Failed to bind properties under 'mongock' to com.github.cloudyrock.spring.v5.MongockConfiguration$$EnhancerBySpringCGLIB$$15c660c2:

    Property: mongock.transaction-enabled
    Value: false
    Origin: class path resource [application.yml]:55:24
    Reason: No setter found for property: transaction-enabled
```

**Comment by dieppa** [comment]
Hello @olivierboudet ,

that's weird because that's actually the fix, add the setter for transactionEnabled, and I am actually running the integration tests agains version 4.1.16 and works fine.

Are you sure if it's not keeping anything in cache?? Can you take a look to your MongockConfiguration and confirm there is no set for that property? you will need to go to the parent class(`ChangockConfiguration`)

**Comment by olivierboudet** [comment]
oh yeah, you are right, Intellij did not refresh correctly.

It's ok :)

Thanks a lot
