### ISSUE TITLE
Configuring a MongockInitializingBeanRunner: never works with MongoTemplate

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [cloudyrock/mongock#250]
I was [following these steps to configure a Bean for `MongockInitializingBeanRunner`](https://github.com/cloudyrock/mongock/issues/195#issuecomment-645593389) (thanks @dieppa), but some of the forms don't work, and this intrigues me. 

The first form I've tried is:

    @Bean
    public MongockSpring5.MongockInitializingBeanRunner mongockInitializingBeanRunner(ApplicationContext springContext) {
        return MongockSpring5.builder()
                .setDriver(SpringDataMongo3Driver.withDefaultLock(mongoTemplate()))
                .addChangeLogsScanPackages(Collections.singletonList("com.my.system.api.changelog"))
                .setSpringContext(springContext)
                .buildInitializingBeanRunner();
    }

This complains that `mongoDatabase` is null here (mongodb-sync-v4-driver-4.1.17.jar!\com\github\cloudyrock\mongock\driver\mongodb\sync\v4\driver\MongoSync4DriverBase.class):

    protected LockRepository getLockRepository() {
        if (this.lockRepository == null) {
            MongoCollection<Document> collection = this.mongoDatabase.getCollection(this.lockCollectionName); // here mongoDatabase is null
            this.lockRepository = new MongoSync4LockRepository(collection, this.indexCreation);
        }

        return this.lockRepository;
    }

Then I tried this, since the Stack Trace reports something at the `MongoSync4Driver`:

    @Bean
    public MongockSpring5.MongockInitializingBeanRunner mongockInitializingBeanRunner(ApplicationContext springContext) {
        return MongockSpring5.builder()
                .setDriver(MongoSync4Driver.withDefaultLock(mongoClient(), "my-database"))
                .addChangeLogsScanPackages(Collections.singletonList("com.my.system.api.changelog"))
                .setSpringContext(springContext)
                .buildInitializingBeanRunner();
    }

This form the Mongo Client complains I'm not using transactional support (which is true, I'm running a Docker image). Finally, I had to use this form:

    @Bean
    public MongockSpring5.MongockInitializingBeanRunner mongockInitializingBeanRunner(ApplicationContext springContext) {
        return MongockSpring5.builder()
                .setDriver(SpringDataMongo3Driver.withDefaultLock(mongoClient(), "my-database"))
                .addChangeLogsScanPackages(Collections.singletonList("com.my.system.api.changelog"))
                .setSpringContext(springContext)
                .buildInitializingBeanRunner();
    }

And add this:

    @Bean
    public GridFsTemplate gridFsTemplate(MongoDatabaseFactory mongoDatabaseFactory, MongoConverter mongoConverter) {
        return new GridFsTemplate(mongoDatabaseFactory, mongoConverter);
    }

This works. My questions are:

1. Why it doesn't work with `MongoTemplate`?
2. Why does it work with the `MongoClient` + database name, since I declare my `MongoTemplate` bean like this?

        public @Bean MongoTemplate mongoTemplate() {
            return new MongoTemplate(mongoClient(), "my-database");
        }

**Comment by leonelsanchesdasilva** [comment]
Well, now I think this is a bug. 

pom.xml:

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-bom</artifactId>
            <version>4.1.17</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
            <version>4.1.17</version>
        </dependency>
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
            <version>4.1.17</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
            <version>2.3.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
            <version>2.3.2.RELEASE</version>
        </dependency>

## Scenario 1: Only using `@EnableMongock` at my Application Setup

```
@EnableMongock
@SpringBootApplication
@ComponentScan(basePackages = {"com.my.system"})
public class MySystemApiApplication {

	public static void main(String[] args) {
		SpringApplication.run(MySystemApiApplication.class, args);
	}

}
```

Error executing Maven Tests:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockConnectionDriver' defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV3CoreContext.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.SpringDataMongo3Driver]: Factory method 'mongockConnectionDriver' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120) ~[spring-boot-test-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) ~[spring-test-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 46 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.SpringDataMongo3Driver]: Factory method 'mongockConnectionDriver' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 65 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.driver.MongoSync4DriverBase.getLockRepository(MongoSync4DriverBase.java:106) ~[mongodb-sync-v4-driver-4.1.17.jar:na]
	at io.changock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:37) ~[changock-driver-core-1.1.6.jar:na]
	at com.github.cloudyrock.spring.v5.MongockSpringDataCoreContextBase.setUpMongockConnectionDriver(MongockSpringDataCoreContextBase.java:23) ~[mongock-spring-v5-4.1.17.jar:na]
	at com.github.cloudyrock.spring.v5.MongockSpringDataV3CoreContext.mongockConnectionDriver(MongockSpringDataV3CoreContext.java:29) ~[mongock-spring-v5-4.1.17.jar:na]
	at com.github.cloudyrock.spring.v5.MongockSpringDataV3CoreContext$$EnhancerBySpringCGLIB$$4f93ddfd.CGLIB$mongockConnectionDriver$1(<generated>) ~[mongock-spring-v5-4.1.17.jar:na]
	at com.github.cloudyrock.spring.v5.MongockSpringDataV3CoreContext$$EnhancerBySpringCGLIB$$4f93ddfd$$FastClassBySpringCGLIB$$d2db4d4e.invoke(<generated>) ~[mongock-spring-v5-4.1.17.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.github.cloudyrock.spring.v5.MongockSpringDataV3CoreContext$$EnhancerBySpringCGLIB$$4f93ddfd.mongockConnectionDriver(<generated>) ~[mongock-spring-v5-4.1.17.jar:na]
	at jdk.internal.reflect.GeneratedMethodAccessor176.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 66 common frames omitted
```

## Scenario 2: Removed `@EnableMongock` at my Application Setup, Configured Beans

Beans:

```
@Configuration
@Profile("!test")
public class DatabaseConfiguration {

    @Value("${spring.data.mongodb.host}")
    private String mongoHost;

    @Value("${spring.data.mongodb.port}")
    private String mongoPort;

    public @Bean
    MongoClient mongoClient() {
        return MongoClients.create("mongodb://" + mongoHost + ":" + mongoPort);
    }

    public @Bean MongoTemplate mongoTemplate() {
        return new MongoTemplate(mongoClient(), "my-database");
    }

    @Bean
    public MongockSpring5.MongockInitializingBeanRunner mongockInitializingBeanRunner(ApplicationContext springContext) {
        return MongockSpring5.builder()
                .setDriver(SpringDataMongo3Driver.withDefaultLock(mongoClient(), "my-database"))
                .addChangeLogsScanPackages(Collections.singletonList("com.my.system.api.changelog"))
                .setSpringContext(springContext)
                .buildInitializingBeanRunner();
    }

    @Bean
    public GridFsTemplate gridFsTemplate(MongoDatabaseFactory mongoDatabaseFactory, MongoConverter mongoConverter) {
        return new GridFsTemplate(mongoDatabaseFactory, mongoConverter);
    }
}
```

Running Maven Tests:

Same error as the previous case.

**Comment by dieppa** [comment]
We'll taking a look to this as soon as possible and will let you know

**Comment by mraible** [comment]
@dieppa This issue is affecting the JHipster project and I'd like to help get it fixed. We have money we can donate to this project if it helps.

**Comment by dieppa** [comment]
Hi @mraible , thanks for the money, but there is no need. Having Mongock's logo in JHipster site once is released is enough :).

I am actually taking this tomorrow(now with more reason). I think I can release a bugfix tomorrow evening.

**Comment by dieppa** [comment]
Hello @leonelsanchesdasilva ,

I've created a dummy project for this. I am probably missing something, but I am not able to reproduce it. Can you take a quick look at [project issue_250 ](https://github.com/dieppa/mongock-issue-250) and tell me what I need to do to reproduce it?

**Comment by leonelsanchesdasilva** [comment]
@dieppa very tricky to simulate in your project for some reason, but I noted that only my tests with mocking `mongoTemplate` give problems. Good to say, you'll need to implement custom repositories. Something like this:

```
package com.github.cloudyrock.mongock.issue_250.repositories;

import com.github.cloudyrock.mongock.issue_250.MongockIssue250ApplicationTests;
import com.github.cloudyrock.mongock.issue_250.client.repositories.ClientRepository;
import com.github.cloudyrock.mongock.issue_250.client.repositories.ClientRepositoryImpl;
import org.junit.Before;
import org.junit.runner.RunWith;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@AutoConfigureMockMvc
public class ClientRepositoryTests extends MongockIssue250ApplicationTests {

    private ClientRepository clientRepository;

    @MockBean
    private MongoTemplate mongoTemplate;

    @Before
    public void setUp() {
        clientRepository = new ClientRepositoryImpl(mongoTemplate);
    }
}
```

and:

```
package com.github.cloudyrock.mongock.issue_250.client.repositories;

import com.github.cloudyrock.mongock.issue_250.client.models.Client;

import java.util.List;

public interface ClientRepository {
    List<Client> getAllClients();

    Client insertClient(Client client);
}
```

and:

```
package com.github.cloudyrock.mongock.issue_250.client.repositories;

import com.github.cloudyrock.mongock.issue_250.client.models.Client;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;

import java.util.List;

public class ClientRepositoryImpl implements ClientRepository {
    private MongoTemplate mongoTemplate;

    @Autowired
    public ClientRepositoryImpl(MongoTemplate mongoTemplate) {
        this.mongoTemplate = mongoTemplate;
    }

    @Override
    public List<Client> getAllClients() {
        return mongoTemplate.findAll(Client.class);
    }

    @Override
    public Client insertClient(Client client) {
        mongoTemplate.insert(client);
        return client;
    }
}
```

Running the tests, you'll have something like this:

![image](https://user-images.githubusercontent.com/53848829/93824473-5b560480-fc18-11ea-9ae3-576f974a6c8f.png)

I'm still trying to make a source where the problem is easy to reproduce, but all the tests are passing so far.

**Comment by leonelsanchesdasilva** [comment]
I forgot this one:

```
package com.github.cloudyrock.mongock.issue_250;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest(classes = MongockIssue250ApplicationTests.class)
public class MongockIssue250ApplicationTests {

    @Test
    public void contextLoads() {
    }
}
```

**Comment by leonelsanchesdasilva** [comment]
For now I'm having to use something like this for my tests:

```
package test.my.app.api;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.test.context.TestPropertySource;

@SpringBootTest(classes = MyAppApplicationTests.class)
@ComponentScan("com.my.app.api")
@TestPropertySource(properties=
        {"mongock.enabled=false"})
public class MyAppApplicationTests {

    @Test
    public void contextLoads() {
    }

}
```

**Comment by dieppa** [comment]
ok, I will try to take  all that and reproduce it. If you can share your pom, that would be great too.

**Comment by leonelsanchesdasilva** [comment]
Sure thing.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.2.RELEASE</version>
        <relativePath/>
    </parent>
    <groupId>com.my.app</groupId>
    <artifactId>my-app</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>my-app</name>
    <description>My App.</description>

    <properties>
        <java.version>11</java.version>
        <!-- Sonar -->
        <sonar.branch.name>master</sonar.branch.name>
        <sonar.coverage.exclusions>
            **/pom.xml,
            **/application.properties,
            **/log4j2.xml,
            **/Dockerfile,
            **/Jenkinsfilescan
        </sonar.coverage.exclusions>
        <sonar.junit.reportPath>target/surefire-reports</sonar.junit.reportPath>
        <sonar.maven.plugin.version>3.4.0.905</sonar.maven.plugin.version>
        <jacoco.outputDir>${project.build.directory}</jacoco.outputDir>
    </properties>

    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <activatedProperties>dev</activatedProperties>
            </properties>

        </profile>
        <profile>
            <id>test</id>
            <properties>
                <activatedProperties>test</activatedProperties>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
            <version>2.3.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
            <version>2.3.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
            <version>2.3.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.3.2.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.javatuples</groupId>
            <artifactId>javatuples</artifactId>
            <version>1.2</version>
        </dependency>

        <dependency>
            <groupId>de.undercouch</groupId>
            <artifactId>bson4jackson</artifactId>
            <version>2.9.2</version>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.4.1</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.13.2</version>
        </dependency>

        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.9.1</version>
        </dependency>

        <dependency>
            <groupId>com.bettercloud</groupId>
            <artifactId>vault-java-driver</artifactId>
            <version>5.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
            <version>4.1.4</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.0.9</version>
        </dependency>

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-bom</artifactId>
            <version>4.1.17</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
            <version>4.1.17</version>
        </dependency>
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
            <version>4.1.17</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <!-- Sonar Plugin-->
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>3.6.0.1398</version>
            </plugin>

            <!-- Maven Checkstyle-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.1.1</version>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.3.2.RELEASE</version>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.5</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
        </pluginRepository>
        <pluginRepository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</project>
```

**Comment by dieppa** [comment]
Hello @leonelsanchesdasilva ,

I have copied your source into the temp project I created to reproduce the issue in this [branch](https://github.com/dieppa/mongock-issue-250/compare/reproduce_issue?expand=1).


I was able to reproduce the problem. I share the [mvn test stack trace](https://github.com/cloudyrock/mongock/files/5261125/stack_trace.log) just to be 100% sure we speak about the same issue, but I am pretty confident.

I maybe missing something, but it's totally normal you get an "empty" MongoTemplate bean in `MongockSpringDataV3CoreContext` as you show in that image. That is due to the fact that you are mocking the MongoTemplate. That mock is the one injected to the context, and the one used by Mongock's driver. As you haven't configured the mock, when Mongock's driver tries to get the mongoDatabase, it returns null and that's error.

I have made a small change you can see in that project I mentioned, class `ClientRepositoryIntegrationTest`, line 23 and 24. I just changed @MockBean for @Autorwired and works, all tests passed.

If you really need to mock the MongoTemplate, you need to ensure you configured accordingly, so the other dependent components(among others, Mongock) work ok.


I hope that solves your issue. If I missed something or you still struggle, please, let me know :)

**Comment by dieppa** [comment]
And please let me know something as soon as you can. JHipster guys (@mraible, @DanielFran and @pascalgrimaud) are waiting for this and I am not sure their issue is related to this :)

**Comment by dieppa** [comment]
Hi @leonelsanchesdasilva , confirmed, JHipster's issue wasn't related to this one and it has been fixed on their side.
Can you tell me something about this when you can? We'd don't like to have open issues without any move.

Thanks  :)

**Comment by leonelsanchesdasilva** [comment]
@dieppa I think we can close this story now. Perhaps the history of this issue is good enough for people that can have the same problem in the future, or we can add special guidance somewhere when using Mongock with unit testing. I can help with this.

**Comment by dieppa** [comment]
Thanks @leonelsanchesdasilva , I think you are right and actually both. Adding it to a FAQ page and also and special guidance for testing, as you suggest.

If you'd like to contribute in this or anything else, please let me know privately at antonio@cloudyrock.io

Thanks.
