### ISSUE TITLE
Error during migration from Mongobee : Forbidden parameter[MongoTemplate]. Must be replaced with [MongockTemplate]

### ISSUE THREAD

**Issue by GregBoero** [cloudyrock/mongock#254]
switching from Mongobee to Mongork on a Spring fromworks application (Not Spring Boot), i've updated the code 
 
```

        MongockLegacyMigration legacyMigration = new MongockLegacyMigration();
        legacyMigration.setCollectionName("dbchangelog");

        SpringDataMongo3Driver driver = SpringDataMongo3Driver.withDefaultLock(mongoTemplate);
        driver.setLockCollectionName("mongobeelock");

        return MongockSpring5.builder()
            .setDriver(driver)
            .addChangeLogsScanPackage(this.mongoProperties.getMongobeeScanPackage())
            .setSpringContext(springContext)
            .setLegacyMigration(legacyMigration)
            .buildInitializingBeanRunner();
```

and it throw the following error : 

```
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: io.changock.migration.api.exception.ChangockException: Error in method[InitChangelog.initContacts] : Forbidden parameter[MongoTemplate]. Must be replaced with [MongockTemplate]
	at io.changock.runner.core.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:195)
	at io.changock.runner.core.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:102)
	at io.changock.runner.core.MigrationExecutor.lambda$processSingleChangeLog$2(MigrationExecutor.java:94)
	at io.changock.runner.core.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:80)
	at io.changock.runner.core.MigrationExecutor.processSingleChangeLog(MigrationExecutor.java:94)
	at io.changock.runner.core.MigrationExecutor.lambda$processAllChangeLogs$1(MigrationExecutor.java:88)
	at io.changock.runner.core.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:80)
	at io.changock.runner.core.MigrationExecutor.processAllChangeLogs(MigrationExecutor.java:88)
	at io.changock.runner.core.MigrationExecutor.lambda$executeMigration$0(MigrationExecutor.java:69)
	at io.changock.runner.core.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:80)
	at io.changock.runner.core.MigrationExecutor.executeMigration(MigrationExecutor.java:69)
	at io.changock.runner.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:38)
	at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:44)
	at io.changock.runner.spring.v5.ChangockSpringBuilderBase$ChangockSpringInitializingBeanRunner.afterPropertiesSet(ChangockSpringBuilderBase.java:125)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	... 43 more
Caused by: io.changock.driver.api.common.ForbiddenParameterException: Forbidden parameter[MongoTemplate]. Must be replaced with [MongockTemplate]
	at io.changock.driver.api.driver.ForbiddenParametersMap.throwExceptionIfPresent(ForbiddenParametersMap.java:18)
	at io.changock.runner.core.DependencyManager.getDependency(DependencyManager.java:36)
	at io.changock.runner.core.DependencyManagerWithContext.getDependency(DependencyManagerWithContext.java:32)
	at io.changock.runner.core.MigrationExecutor.getParameter(MigrationExecutor.java:181)
	at io.changock.runner.core.MigrationExecutor.executeChangeSetMethod(MigrationExecutor.java:171)
	at io.changock.runner.core.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:127)
	at io.changock.runner.spring.v5.core.SpringMigrationExecutor.executeAndLogChangeSet(SpringMigrationExecutor.java:44)
	at io.changock.runner.core.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:100)
```

I see nothing in the documentation about this.

**Comment by dieppa** [comment]
As the error message says, you must replace all your MongoTemplate parameters in your changeSets by MongockTemplate. If you see [this part of the documentation](https://www.mongock.io/changelogs), you can see it ;). You won't have any problem, it provides the same API
