### ISSUE TITLE
Issues when migrating from mongobee to mongock

### ISSUE THREAD

**Issue by mafupi** [cloudyrock/mongock#260]
I am trying to migrate from mongobee to mongock in order to upgrade springboot but run into the following error when the application is starting:
```
The bean 'mongockConnectionDriver', defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV3CoreContext.class], could not be registered. A bean with that name has already been defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV2CoreContext.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Uncaught exception - org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'mongockConnectionDriver' defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV3CoreContext.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=mongockSpringDataV3CoreContext; factoryMethodName=mongockConnectionDriver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV3CoreContext.class]] for bean 'mongockConnectionDriver': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=mongockSpringDataV2CoreContext; factoryMethodName=mongockConnectionDriver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV2CoreContext.class]] bound.
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'mongockConnectionDriver' defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV3CoreContext.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=mongockSpringDataV3CoreContext; factoryMethodName=mongockConnectionDriver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV3CoreContext.class]] for bean 'mongockConnectionDriver': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=mongockSpringDataV2CoreContext; factoryMethodName=mongockConnectionDriver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/github/cloudyrock/spring/v5/MongockSpringDataV2CoreContext.class]] bound.
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:945)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:286)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:96)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
```

My dependency setup:
```
implementation 'com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:4.1.17'
implementation 'com.github.cloudyrock.mongock:mongock-spring-v5:4.1.17'
implementation 'org.springframework.data:spring-data-mongodb:3.0.0.RELEASE'
implementation group: 'org.mongodb', name: 'mongodb-driver-sync', version: '4.1.1'
```

Springboot: 2.3.4.RELEASE

**Comment by dieppa** [comment]
Hello @mafupi ,

from your log trace it seems you are importing both, `MongockSpringDataV3CoreContext` and `mongockSpringDataV2CoreContext`. You should only import one, in this case `MongockSpringDataV3CoreContext` which belongs to `com.github.cloudyrock.mongock:mongodb-springdata-v3-driver`.

**Comment by mafupi** [comment]
@dieppa, agree but I cannot figure out which dependency is pulling mongockSpringDataV2CoreContext. The code will not compile without any of the above.

**Comment by dieppa** [comment]
could you show me the dependencies you are importing(not only Mongock)

**Comment by mafupi** [comment]
https://docs.google.com/document/d/1DDObHYfPFfN1PhC5B_WIn2V3C2mEfEPpUG1Le4NrLRY/edit?usp=sharing

**Comment by dieppa** [comment]
I just tried and couldn't reproduce it.
I used
```xml

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.cloudyrock.mongock</groupId>
                <artifactId>mongock-bom</artifactId>
                <version>4.1.17</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.3.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
        </dependency>


        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-sync</artifactId>
            <version>${mongodb.driver-sync.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-mongodb</artifactId>
            <version>${mongodb.spring-data.v3.version}</version>
        </dependency>
        <!-- ... -->
</dependencies>

```

**Comment by dieppa** [comment]
ok, lets do this, Please do `mvn dependency:sources` and show me what it prints ;)

**Comment by dieppa** [comment]
sorry, `mvn depdency:tree`

**Comment by dieppa** [comment]
sorry again,. you are using gradle. I think it's `app:dependencies`

**Comment by mafupi** [comment]
I am using gradle. The list is very long so I put it here https://docs.google.com/document/d/1vkRU_S_1VebIZutrNUwaB6yWCOlIvjbkYl78Lyuk9gI/edit?usp=sharing

**Comment by mafupi** [comment]
A better version: https://gradle.com/s/rvgntovskgldw

**Comment by dieppa** [comment]
Ok, I will try to reproduce. I will update you later.

**Comment by mafupi** [comment]
I am not using auto config but instead a bean:

```
    @Bean
    public MongockSpring5.MongockApplicationRunner mongockApplicationRunner(
            ApplicationContext springContext,
            MongoTemplate mongoTemplate) {
        return MongockSpring5.builder()
                .setDriver(SpringDataMongo3Driver.withDefaultLock(mongoTemplate))
                .addChangeLogsScanPackage("<baseClassForChangeLogs>")
                .setSpringContext(springContext)
                .buildApplicationRunner();
    }
```

**Comment by dieppa** [comment]
Hello @mafupi ,

I can only manage to (kind of) reproduce it if I create the bean, as you indicate, and use @EnableMongock. If I remove any of them, it works fine for me

**Comment by mafupi** [comment]
Interesting it works for you? What JDK and springboot? I am on Java 11.0.7 and springboot 2.3.4.RELEASE, though I tried 2.2.6 as well without success

**Comment by dieppa** [comment]
```xml

        <mongodb.spring-data.v3.version>3.0.0.RELEASE</mongodb.spring-data.v3.version>
        <mongodb.driver-sync.version>4.0.2</mongodb.driver-sync.version>
```

and java 8.


I will try java 11, but can't now. It has to be during the weekend.

**Comment by mafupi** [comment]
Experimenting a bit I found that removing the dependency 
```implementation group: 'com.github.cloudyrock.mongock', name: 'mongock-spring-v5', version: '4.1.17'```

seems to eliminate the error but obviously causes another problem down the line:

```Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.decorator.impl.MongockTemplate' available```

**Comment by mafupi** [comment]
I think I can say with confidence that the conflict is between these two dependencies:
```implementation 'com.github.cloudyrock.mongock:mongock-spring-v5:4.1.17'
implementation 'com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:4.1.17'```

And I need both of them it seems

**Comment by dieppa** [comment]
Hello @mafupi , sorry we have been very busy. I'll try to come back to you by Monday.

**Comment by dieppa** [comment]
Hello again,

I have been trying to reproduce the error, but no luck so far. I am using Java 11 with a Mongock configuration that I think it's very similar to what you have, but works fine for me.


So I think the best shoot is you to clone this [multiproject](https://github.com/cloudyrock/mongock-integration-tests), change to branch `mongock_issue_260`, then, once cloned and in the right branch, go to this [subproject](https://github.com/cloudyrock/mongock-integration-tests/tree/master/mongock-4/mongock-spring-v5/mongock-spring5-springdata3-it).

The first thing you can do is to run it to verify everything goes well. If not, then we found it quicker than I expected. If everything is ok, as expected, please perform the changes in that project(similar to what you have in yours) to reproduce it. And then let me know so I can see what is going on.

Cheers

**Comment by dieppa** [comment]
Hello @mafupi , are you still facing this issue?

Cheers

**Comment by mafupi** [comment]
Hello @dieppa 
Apologies I could not get back to you on this. Due to other commitments, I have parked this for a while. I will try your suggestion once I get some time. In the meantime, I guess we can close this if needed.

**Comment by ckmoga** [comment]
The issue turned out to be with scanBasePackages. After changing
`@SpringBootApplication(scanBasePackages={"com.*"})`

to

`@SpringBootApplication(scanBasePackages={"com.myorg.*"})`

the was resolved
