### ISSUE TITLE
Mongock fails with MongoDB v4.4.1

### ISSUE THREAD

**Issue by FahuPt** [cloudyrock/mongock#263]
I've been using Mongock with Mongodb v4.2 it works great for us. Recently the db has been upgraded to v4.4.1. Since the upgrade Mongock failed work with MongoDB version 4.4.1

`  @Bean
    public MongockSpring5.MongockApplicationRunner mongockApplicationRunner(final ApplicationContext springContext, final MongoTemplate mongoTemplate) {
        return MongockSpring5.builder()
                .setDriver(SpringDataMongo3Driver.withDefaultLock(mongoTemplate))
                .addChangeLogsScanPackage(MIGRATION_PACKAGE_PATH)
                .setSpringContext(springContext)
                .buildApplicationRunner();
    }`

Error:

`io.changock.migration.api.exception.ChangockException: Max tries 3 index  creation
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:46) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:56) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:56) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:56) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.initialize(MongoSync4RepositoryBase.java:39) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at io.changock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:38) ~[changock-driver-core-1.1.3.jar:na]
        at io.changock.runner.core.MigrationExecutor.initializationAndValidation(MigrationExecutor.java:188) ~[changock-runner-core-1.1.3.jar:na]
        at io.changock.runner.spring.v5.core.SpringMigrationExecutor.initializationAndValidation(SpringMigrationExecutor.java:31) ~[changock-spring-v5-runner-1.1.3.jar:na]
        at io.changock.runner.core.MigrationExecutor.executeMigration(MigrationExecutor.java:60) ~[changock-runner-core-1.1.3.jar:na]
        at io.changock.runner.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37) ~[changock-spring-v5-runner-1.1.3.jar:na]
        at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:44) ~[changock-runner-core-1.1.3.jar:na]
        at io.changock.runner.spring.v5.ChangockSpringBuilderBase$ChangockSpringApplicationRunner.run(ChangockSpringBuilderBase.java:109) ~[changock-spring-v5-runner-1.1.3.jar:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at com.myapp.bo.auth.MyApplication.main(MyApplication.java:16) ~[classes/:na]

2020-11-02 19:51:41.133 ERROR [,,,] 72458 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at com.myapp.bo.auth.MyApplication.main(MyApplication.java:16) ~[classes/:na]
Caused by: io.changock.migration.api.exception.ChangockException: Max tries 3 index  creation
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:46) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:56) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:56) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.ensureIndex(MongoSync4RepositoryBase.java:56) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at com.github.cloudyrock.mongock.driver.mongodb.sync.v4.repository.MongoSync4RepositoryBase.initialize(MongoSync4RepositoryBase.java:39) ~[mongodb-sync-v4-driver-4.1.12.jar:na]
        at io.changock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:38) ~[changock-driver-core-1.1.3.jar:na]
        at io.changock.runner.core.MigrationExecutor.initializationAndValidation(MigrationExecutor.java:188) ~[changock-runner-core-1.1.3.jar:na]
        at io.changock.runner.spring.v5.core.SpringMigrationExecutor.initializationAndValidation(SpringMigrationExecutor.java:31) ~[changock-spring-v5-runner-1.1.3.jar:na]
        at io.changock.runner.core.MigrationExecutor.executeMigration(MigrationExecutor.java:60) ~[changock-runner-core-1.1.3.jar:na]
        at io.changock.runner.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37) ~[changock-spring-v5-runner-1.1.3.jar:na]
        at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:44) ~[changock-runner-core-1.1.3.jar:na]
        at io.changock.runner.spring.v5.ChangockSpringBuilderBase$ChangockSpringApplicationRunner.run(ChangockSpringBuilderBase.java:109) ~[changock-spring-v5-runner-1.1.3.jar:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        ... 5 common frames omitted
`
Any help on this is much appreciated. Thanks in Adv!

**Comment by dieppa** [comment]
Hello @FahuPt 
thanks for this. It's an important one. We'll take a look and we'll try to release a bugfix during the week, probably Friday

**Comment by FahuPt** [comment]
Thank you @dieppa!

**Comment by FahuPt** [comment]
Hi @dieppa - Just wanted to check if you got a chance to have a look into this issue :)

**Comment by dieppa** [comment]
Hello, sorry, I was actually planning of taking a loom this afternoon. Will keep you updated

**Comment by dieppa** [comment]
Hello @FahuPt ,

I have tried to reproduce it without success. Can you tell me which Mongock and Spring boot version you're using?

**Comment by FahuPt** [comment]
Hi @dieppa 
Here is the details

**Java 11**
**MongoDB 4.4.1**

`<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.0.RELEASE</version>
        <relativePath/> 
    </parent>

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
            <version>4.1.12</version>
        </dependency>

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
            <version>4.1.12</version>
        </dependency>
`
I have verified the indexes in 'mongockLock' collection. It was created successfully

Tried with latest version as well. But same result.

Thanks in Adv!

**Comment by dieppa** [comment]
Hello @FahuPt ,

sorry for the delay in the answer. Your problem was fixed in the [release 4.1.5](https://github.com/cloudyrock/mongock/releases/tag/mongock-4.1.15), [issue 234](https://github.com/cloudyrock/mongock/issues/234).

However, although it fixed in version 4.1.15, my suggestion is you to upgrade to the last version 4.1.19
