### ISSUE TITLE
Transaction enabled migrations always complete successfully even if migration failed. 

### ISSUE THREAD

**Issue by stikku** [cloudyrock/mongock#303]
### Description

When mongock is configured to use transactions, and the migration fails for any reason; the migration gets rolled back (as excepted), but the error is not rethrown. This results in the migration to appear as successful even thou no changes where performed.

### PRIORITY

CRITICAL - it is not feasable to use mongock transactions as you would not know whether the transaction was completed successfully and thus the rest of the application cannot depend on the migration.

### Steps to Reproduce

1. Enable mongock transactions.
2. Write migration that fails.
3. Start application.

### Specific scenario

We use Mongock to trigger migrations during application startup. Should the migration fail we expect the application to fail startup, but this is not possible due to this issue.
In our scenario it is required to use transactional migrations since we have a high availability environment and other instances of our application might access the database in parallel.

**Expected behavior:** On failure of transactional migration we expect to either receive the `SpringMigrationFailureEvent` or ideally have the migration process fail, in addition to the existing database rollback.

**Actual behavior:** Transactional migration completes successfully event if it actually failed and rolled back. 

**Reproduces how often:** on failure 100%

### Version
```
      <dependency>
        <groupId>com.github.cloudyrock.mongock</groupId>
        <artifactId>mongock-spring-v5</artifactId>
        <version>4.3.5</version>
      </dependency>
      <dependency>
        <groupId>com.github.cloudyrock.mongock</groupId>
        <artifactId>mongodb-springdata-v3-driver</artifactId>
        <version>4.3.5</version>
      </dependency>
```

### Additional Information

Having reviewed the open source code we believe we have identified the source of this issue.
In [SpringDataMongoV3Driver#executeInTransaction ln 112](https://github.com/cloudyrock/mongock/blob/master/mongodb-springdata-v3-driver/src/main/java/com/github/cloudyrock/mongock/driver/mongodb/springdata/v3/SpringDataMongoV3Driver.java#L112) an exception that happens within the transaction is being caught in order to be able to rollback. In this catch (after the rollback) I would expect that the exception would be rethrown such as `throw new MongockException(ex)` . This would be similar behaviour to the parent implementation in [MongoSync4DriverBase](https://github.com/cloudyrock/mongock/blob/master/mongodb-sync-v4-driver/src/main/java/com/github/cloudyrock/mongock/driver/mongodb/sync/v4/driver/MongoSync4DriverBase.java#L168).

The same issue seems to be present (not tested) in [SpringDataMongoV2Driver](https://github.com/cloudyrock/mongock/blob/master/mongodb-springdata-v2-driver/src/main/java/com/github/cloudyrock/mongock/driver/mongodb/springdata/v2/SpringDataMongoV2Driver.java#L102)

Sample fix  [SpringDataMongoV3Driver#executeInTransaction](https://github.com/cloudyrock/mongock/blob/master/mongodb-springdata-v3-driver/src/main/java/com/github/cloudyrock/mongock/driver/mongodb/springdata/v3/SpringDataMongoV3Driver.java#L112)
```
  @Override
  public void executeInTransaction(Runnable operation) {
    TransactionStatus txStatus = getTxStatus(txManager);
    try {
      mongoTemplate.setSessionSynchronization(SessionSynchronization.ALWAYS);
      operation.run();
      txManager.commit(txStatus);
    } catch (Exception ex) {
      logger.warn("Error in Mongock's transaction", ex);
      txManager.rollback(txStatus);
      throw new MongockException(ex);
    }

  }
```

**Comment by dieppa** [comment]
Thank you @stikku , it's already identified and will be released in the version 4.3.6.

Thanks

**Comment by stikku** [comment]
@dieppa I have tried running my application with using mongock master (built locally) `4.3.6-SNAPSHOT` and I am encountering the same issue. I assume the fix is yet to be merged? 

Since this issue is a blocking us from deploying some changes to our own application, would you have a rough estimate of when 4.3.6 will be released? or when it will be available on master so we can test it?

Thank you a lot for your assistance and we would be happy to provide any help in solving this issue.

**Comment by dieppa** [comment]
Ah sorry, it's not provided yet in that version.

Unless something unexpected happen, tomorrow will be released ;)

**Comment by dieppa** [comment]
Hello @stikku , can you clone check the branch issue/303? You just need to build it locally and update the mongock-bom version to 4.3.6.SNAPSHOT

**Comment by dieppa** [comment]
Hello @stikku ,

can you checkout the branch issue/303, build locally and confirm the issues is fixed. We have added it to our integration tests, but I prefer you to check first.(next time we'll provide an snapshot version)

Thanks

**Comment by stikku** [comment]
Hello @dieppa 

I have built locally as follows:
mongock -> branch issue/303
mongock-core -> master

And I received the following error during spring startup:
```
2021-03-04 13:28:08.311  WARN 59182 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.github.cloudyrock.spring.v5.config.MongockContext]; nested exception is java.io.FileNotFoundException: class path resource [com/github/cloudyrock/mongock/driver/mongodb/springdata/v3/SpringDataMongoV3Context.class] cannot be opened because it does not exist
2021-03-04 13:28:08.329  INFO 59182 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-04 13:28:08.370 ERROR 59182 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.github.cloudyrock.spring.v5.config.MongockContext]; nested exception is java.io.FileNotFoundException: class path resource [com/github/cloudyrock/mongock/driver/mongodb/springdata/v3/SpringDataMongoV3Context.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:311)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:600)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:311)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:304)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:336)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:252)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:285)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:99)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at com.main(Main.java:10)
Caused by: java.io.FileNotFoundException: class path resource [com/github/cloudyrock/mongock/driver/mongodb/springdata/v3/SpringDataMongoV3Context.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:696)
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClasses(ConfigurationClassParser.java:675)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:582)
	... 24 common frames omitted
```

Following the error and seeing recent changes I moved `SpringDataMongoV3Context` and `MongoDBConfiguration` back outside the config directory. Rebuilt and application started successfully.

With regards to this issue (issue 303), mongock looks to be behaving as expected and the issue appear to be resolved on issue/303 branch.

**Comment by dieppa** [comment]
sorry, my mistake. Can you  clone the[ mongock-core project,](https://github.com/cloudyrock/mongock-core), branch issue/303, build it and pull and build the mongock project again. You should use the version 4.3.7.SNAPSHOT

**Comment by stikku** [comment]
@dieppa 

Updated local branches to:
mongock -> branch issue/303
mongock-core -> branch issue/303

tested it and all looks good.
Thanks a lot for your support

**Comment by dieppa** [comment]
Thanks.

The version 4.3.7 will be released soon. I keep you updated

**Comment by dieppa** [comment]
Version 4.3.7 is released.

I close this ticket.

Thanks @stikku
