### ISSUE TITLE
Error creating mongock bean when deploying on docker

### ISSUE THREAD

**Issue by baphuc1998** [cloudyrock/mongock#308]
I am using Mongck to migrate data in my Spring Boot application. Spring Boot application runs perfectly locally. But when running on docker, the following error occurs:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [vn/vnpt/icode/svc/config/config/MongockConfig.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/mongodb/MongoDatabaseFactory

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]

at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]

at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]

at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]

at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]

at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]

at vn.vnpt.icode.svc.config.Application.main(Application.java:13) ~[classes!/:na]

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]

at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]

at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[svc-config-1.0.0.jar:na]

at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[svc-config-1.0.0.jar:na]

at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[svc-config-1.0.0.jar:na]

at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[svc-config-1.0.0.jar:na]

Caused by: java.lang.NoClassDefFoundError: org/springframework/data/mongodb/MongoDatabaseFactory

at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.SpringDataMongo3Driver.specificInitialization(SpringDataMongo3Driver.java:68) ~[mongodb-springdata-v3-driver-4.1.19.jar!/:na]

at io.changock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:44) ~[changock-driver-core-1.1.11.jar!/:na]

at io.changock.runner.core.MigrationExecutor.initializationAndValidation(MigrationExecutor.java:205) ~[changock-runner-core-1.1.11.jar!/:na]

at io.changock.runner.spring.v5.core.SpringMigrationExecutor.initializationAndValidation(SpringMigrationExecutor.java:32) ~[changock-spring-v5-runner-1.1.11.jar!/:na]

at io.changock.runner.core.MigrationExecutor.executeMigration(MigrationExecutor.java:62) ~[changock-runner-core-1.1.11.jar!/:na]

at io.changock.runner.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:38) ~[changock-spring-v5-runner-1.1.11.jar!/:na]

at io.changock.runner.core.ChangockBase.execute(ChangockBase.java:49) ~[changock-runner-core-1.1.11.jar!/:na]

at io.changock.runner.spring.v5.SpringInitializingBean.afterPropertiesSet(SpringInitializingBean.java:21) ~[changock-spring-v5-runner-1.1.11.jar!/:na]

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]

... 24 common frames omitted

Caused by: java.lang.ClassNotFoundException: org.springframework.data.mongodb.MongoDatabaseFactory

at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[na:na]

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[na:na]

at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[svc-config-1.0.0.jar:na]

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]

... 34 common frames omitted
```
Here is the dependencies in build.gradle file:
```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    //implementation 'org.springframework.boot:spring-boot-starter-data-rest'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.cloud:spring-cloud-starter-stream-kafka:3.0.1.RELEASE'
    implementation 'org.springframework.security:spring-security-jwt:1.1.0.RELEASE'
    
    //    implementation 'com.github.mongobee:mongobee:0.13'
    compile group: 'com.github.cloudyrock.mongock', name: 'mongock-bom', version: '4.1.19', ext: 'pom'
    implementation 'com.github.cloudyrock.mongock:mongock-spring-v5:4.1.19'
    implementation 'com.github.cloudyrock.mongock:mongodb-springdata-v3-driver:4.1.19'
    
    implementation 'com.google.code.gson:gson:2.7'
    implementation 'io.minio:minio:7.0.2'
    implementation 'com.hazelcast:hazelcast-kubernetes:2.0'
    implementation 'com.hazelcast:hazelcast-spring'
    implementation 'javax.xml.bind:jaxb-api'
    implementation 'com.google.code.gson:gson:2.7'
    implementation 'net.coobird:thumbnailator:0.4.11'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'io.springfox:springfox-swagger-ui:3.0.0'
    implementation 'io.springfox:springfox-swagger2:3.0.0'
    implementation 'io.springfox:springfox-spring-web:3.0.0'
    implementation 'io.springfox:springfox-oas:3.0.0'
    implementation 'io.swagger:swagger-annotations:1.5.21'
    implementation 'io.swagger:swagger-models:1.5.21'
    implementation 'io.springfox:springfox-boot-starter:3.0.0'
    implementation group: 'org.springframework', name: 'spring-aspects', version: '5.3.4'
    implementation 'com.google.code.gson:gson'
    implementation 'org.apache.commons:commons-collections4:4.1'
    implementation group: 'org.springframework.boot', name: 'spring-boot-configuration-processor', version: '1.2.5.RELEASE'

    
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}
```
Any ideas to help me?

UPDATE: add the content of MongockConfig class:
```java
@Configuration
public class MongckConfig {
    
    @Value("${mongock.change-logs-scan-package}")
    private String changeLogsScanPackage;
    
    @Value("${mongock.enabled}")
    private Boolean mongoEnabled;
    
    @Bean
    @Autowired
    public MongockInitializingBeanRunner mongockInitializingBeanRunner(
        ApplicationContext springContext,
        MongoTemplate mongoTemplate){
        return MongockSpring5.builder()
            .setDriver(SpringDataMongo3Driver.withDefaultLock(mongoTemplate))
            .addChangeLogsScanPackage(changeLogsScanPackage)
            .setSpringContext(springContext)
            .setEnabled(mongoEnabled)
            .buildInitializingBeanRunner();
    }
    
}
```

**Comment by dieppa** [comment]
It's probably not the reason, but upgrade mongock to version 4.3.7 and let me know how it goes.

**Comment by baphuc1998** [comment]
> ut upgrade mongock to version 4.3.7 and let me know how it g

Everything's fine after I upgrade Mongock to version 4.3.7 in Spring Boot 2.4.1. Thanks for your help ^^

**Comment by dieppa** [comment]
hi @baphuc1998 , We have solved your question in [stackoverflow](https://stackoverflow.com/questions/66610729/error-creating-mongock-bean-when-deploying-on-docker/66630199#66630199) too. If you can please vote for our answer as useful, would be really appreciated.
