### ISSUE TITLE
springboot 2.1.10.RELEASE is not compatible

### ISSUE THREAD

**Issue by qq214516448** [cloudyrock/mongock#326]
system condition :
 springboot  2.1.10.RELEASE

i had try mongock-bom 4.3.+ and 4.2.+ 
but it get error:
```
java.lang.NoSuchMethodException: com.github.cloudyrock.spring.v5.config.MongockDriverContextSelector.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349) ~[na:na]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:122) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	... 21 common frames omitted 
```

then i try to work in version 4.1.19 or 4.1.18  it can start spring boot now. however, my configuration file `InitializerChangeLog` , which has been annnotationed by ChangeLog & ChangeSet , does not be  load by mongock. I debug and find it seems it does not work in a method **mergeChangeLogClassesAndPackages()**. This method can not load my configuration file. 

i try to work in version  4.1.8,
it come acrosss ：
```
io.changock.migration.api.exception.ChangockException: Max tries 3 index  creation
	at com.github.cloudyrock.mongock.driver.mongodb.v3.repository.Mongo3RepositoryBase.ensureIndex(Mongo3RepositoryBase.java:46)
	at com.github.cloudyrock.mongock.driver.mongodb.v3.repository.Mongo3RepositoryBase.ensureIndex(Mongo3RepositoryBase.java:56)
	at com.github.cloudyrock.mongock.driver.mongodb.v3.repository.Mongo3RepositoryBase.ensureIndex(Mongo3RepositoryBase.java:56)
	at com.github.cloudyrock.mongock.driver.mongodb.v3.repository.Mongo3RepositoryBase.ensureIndex(Mongo3RepositoryBase.java:56)
	at com.github.cloudyrock.mongock.driver.mongodb.v3.repository.Mongo3RepositoryBase.initialize(Mongo3RepositoryBase.java:39)
	at io.changock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:38)
……
```

my english is poor. thanks for looking my issue. hope i can get your answers. 
if you can't understand my point or want to know more message, you can leave a message. 

 **i want to know is there any version that is compatible with springboot 2.1.10.RELEASE**

**Comment by dieppa** [comment]
Hello @qq214516448 ,

I am afraid the answer to that is no. 

However, I suggest you to try to use the builder approach as workaround. I believe that will work 😉 

If you need help for the builder, please te a look to our [documentation](https://www.mongock.io/quick-start#traditional-builder-approach). You can inject the `MongockApplicationRunner`/`MongockInitializingBeanRunner` as a bean in your configuration.

Please give a try and let us know

**Comment by qq214516448** [comment]
thanks for your answer.
Firstly, I work with the builder. It got the same problem. 
Then, I try to replace the version of springboot in the official  example. It work ~! So, i think maby is it something wrong with my configuration file. Finally, I found **mongock.change-logs-scan-package** is wrong. Now, I can work with annotation in my project with springboot 2.1.10.RELEASE & mongock-bom 4.1.19 .
lastly, i hope that mongock can  consider compatibility with the old version of springboot when upgrading.
thanks a lot!

**Comment by VincentYuan-hub** [comment]
https://github.com/VincentYuan-hub/monckgo-example
my github had upload this example project. it just replace the version of springboot and spring data .
