### ISSUE TITLE
Can't inject ApplicationContext interface into @ChangeSet method

### ISSUE THREAD

**Issue by sdoxsee** [cloudyrock/mongock#381]
**Describe the bug** 

Can't inject ApplicationContext interface into @ChangeSet method. As this is a data migration, I don't want to inject repositories directly as I plan to delete them in favour of new ones. If I inject repositories directly (at the method signature), I can't delete the interfaces because my migration file won't compile anymore. Please let me know if I'm just going about this the wrong way :/ (actually, I think my reasoning for this approach is off, yet I'm still interested in why ApplicationContext can't be injected)

**To Reproduce**

Steps and conditions to reproduce the behavior:
 - Conditions:
    - Spring Boot 2.5.1, MongoDB driver: 4.2.3, Java 11, MacOs BigSur
    - local. running mvn spring-boot:run
    - Mongock version: 
    - How Mongock is implemented(builder or annotation approach, etc.): @EnableMongock annotation
    - How Mongock is imported: pom starter
    - In general anything in your context that could be affecting
 - Steps
    - All the steps and actions you perform to reproduce the bug 
 ```
    @ChangeSet(order = "009", id = "noop", author = "sdoxsee")
	public void noop(ApplicationContext applicationContext) {
		applicationContext.getBean("permissionRepository");
	}
```

**Expected behavior**

ApplicationContext is an interface, I'd expect it to be injected?

**Logs**
```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.1.jar:2.5.1]
	at com.axaxl.eds.mds.backend.permission.server.Launcher.main(Launcher.java:50) ~[classes/:na]
Caused by: com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog.noop] : Wrong parameter[ApplicationContext]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:215) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:104) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processSingleChangeLog$2(MigrationExecutor.java:96) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeLog(MigrationExecutor.java:96) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processAllChangeLogs$1(MigrationExecutor.java:90) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processAllChangeLogs(MigrationExecutor.java:90) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$executeMigration$0(MigrationExecutor.java:70) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:81) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:70) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37) ~[mongock-spring-v5-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.spring.v5.MongockSpring5$MongockApplicationRunner.run(MongockSpring5.java:68) ~[mongock-spring-v5-4.3.8.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) ~[spring-boot-2.5.1.jar:2.5.1]
	... 5 common frames omitted
Caused by: com.github.cloudyrock.mongock.driver.api.common.DependencyInjectionException: Wrong parameter[ApplicationContext]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$getParameter$4(MigrationExecutor.java:202) ~[mongock-runner-core-4.3.8.jar:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.getParameter(MigrationExecutor.java:202) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeChangeSetMethod(MigrationExecutor.java:191) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:143) ~[mongock-runner-core-4.3.8.jar:na]
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeAndLogChangeSet(SpringMigrationExecutor.java:43) ~[mongock-spring-v5-4.3.8.jar:na]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:102) ~[mongock-runner-core-4.3.8.jar:na]
	... 18 common frames omitted
```

**Comment by dieppa** [comment]
Hello @sdoxsee ,

Why not inject the MongoTemplate(probably for the version  you are using MongockTemplate)? if you are going to delete the permissionRepository, although I guess you will be casting it to a CrudRepository or something like that, still not a good idea. Think that it's possible to run execute that changeLog, when the `perrmissionRepository` is already removed, in an environment in which that changelog hasn't been applied yet. That will break.

I suggest instead, using the MongockTemplate.

We'll investigate the reason  why the ApplicationContext cannot be injected if it's an interface.

**Comment by sdoxsee** [comment]
@dieppa. Excellent idea to just use `MongockTemplate`. In fact, I'm wondering if using interfaces of Repositories, etc is even a good idea. If you ever need to delete it, you'll end up changing the code for the @ChangeLog method...which I don't think is a great idea. I don't think scripts that could have been executed in the past should ever be updated unless they have syntactical errors that would prevent them from being executed altogether.

At least I'll give MongockTemplate a try. 

I'd still like to know why ApplicationContext can't be injected though :/

Thanks!

**Comment by dieppa** [comment]
Yes, I see your point, but that's a mechanism available. The user uses what's is more convenient. Nowadays, most of systems are built based on microservices, with well defined boundaries and componentes, specially the persistent entities and they are not likely to be removed, and therfore the repositories. But if you feel more comfortable by using the MongockTemplate, it's a good approach too 😃 

Just one note, from version5, we have added some improvement in our lock mechanism and you can(and should) use MongoTemplate directly. MongockTemplate is deprecated in this version(but it will never be removed from the code, asyou say, the changeLogs, should be changed).


Regarding the ApplicationContext, I haven't taken a look, but that's makes totally sense as we get the been from the actual ApplicationContext. So far we haven't seen any strong reason to inject the application context too.

I hope all this makes sense to you and I hope you are enjoying using Mongock, anything you feel we should improve, please let us know😃

**Comment by dieppa** [comment]
hi @sdoxsee ,

as you say, when Using MongoTemplate you can use the entity class or raw document objects. That's the good thing about it and Mongock just provide that to you. 

Your case is not a common one, so in your case I guess you should work with Bson documents.

Regarding the best practices, it's a good idea, but once again depends on the user's case, the only think we can do it's list the options and when each of then is best used. We'll do it. Thanks
