### ISSUE TITLE
Startup error with JHipster 

### ISSUE THREAD

**Issue by michael-pratt** [cloudyrock/mongock#44]
I am trying to use mongock as a replacement for Mongobee in a Jhipster application. I have added the following code in place of the Mongobee bean:

```
    @Bean
    public Mongock mongock(ApplicationContext ctx, MongoClient mongoClient, MongoProperties mongoProperties, MongoTemplate mongoTemplate) {
        return new SpringBootMongockBuilder(mongoClient, mongoProperties.getMongoClientDatabase(), "com.elvtn.config.dbmigrations")
            .setApplicationContext(ctx)
            .setLockQuickConfig()
            .setEnabled(true)
            .build();
    }
```

When I run my application, I get this error on startup:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongock' defined in class path resource [com/elvtn/config/DatabaseConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.Mongock]: Factory method 'mongock' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at com.elvtn.App.main(App.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.Mongock]: Factory method 'mongock' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
	... 21 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.github.cloudyrock.mongock.ProxyFactory.createProxyClass(ProxyFactory.java:58)
	at com.github.cloudyrock.mongock.ProxyFactory.createProxyFromOriginal(ProxyFactory.java:99)
	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.build(SpringBootMongockBuilder.java:80)
	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.build(SpringBootMongockBuilder.java:15)
```

This is with JDK8, JHipster 5.5, and Spring Boot 2.

Am initializing the mongock bean properly?

**Comment by michael-pratt** [comment]
Posted too soon. I was using the old mongobee ChangeOrder annotations; changing them to the mongock package solved my problem.

**Comment by dieppa** [comment]
@michael-pratt glad you are using Mongock and you "fixed" your own issue =D
