### ISSUE TITLE
Spring Boot 2.1.5

### ISSUE THREAD

**Issue by bdchatham** [cloudyrock/mongock#72]
Description
I am currently migrating my team's code to Spring Boot 2.1.5. We were previously using MongoBee but are now changing to Mongock (if I can get it to work).

I am getting the below error when running using maven and Intellij...

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
14:56:29.910 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongock-spring-boot' defined in class path resource [com/agilysys/platform/authservice/migration/MigrationConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.SpringBootMongock]: Factory method 'mongock' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.agilysys.platform.authservice.Application.main(Application.java:121)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.SpringBootMongock]: Factory method 'mongock' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 19 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.github.cloudyrock.mongock.ProxyFactory.createProxyClass(ProxyFactory.java:59)
	at com.github.cloudyrock.mongock.ProxyFactory.createProxyFromOriginal(ProxyFactory.java:105)
	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.createMongoDataBaseProxy(SpringBootMongockBuilder.java:72)
	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.createBuild(SpringBootMongockBuilder.java:48)
	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.createBuild(SpringBootMongockBuilder.java:16)
	at com.github.cloudyrock.mongock.MongockBuilderBase.build(MongockBuilderBase.java:148)
	at com.agilysys.platform.authservice.migration.MigrationConfiguration.mongock(MigrationConfiguration.java:34)
	at com.agilysys.platform.authservice.migration.MigrationConfiguration$$EnhancerBySpringCGLIB$$68f5577a.CGLIB$mongock$0(<generated>)
	at com.agilysys.platform.authservice.migration.MigrationConfiguration$$EnhancerBySpringCGLIB$$68f5577a$$FastClassBySpringCGLIB$$dc493876.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.agilysys.platform.authservice.migration.MigrationConfiguration$$EnhancerBySpringCGLIB$$68f5577a.mongock(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
	at net.sf.cglib.core.DebuggingClassWriter.<init>(DebuggingClassWriter.java:49)
	at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24)
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174)
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
	... 37 common frames omitted

Process finished with exit code 1
```

And my @Configuration class looks like...

```
@Configuration
public class MigrationConfiguration {

    private static final String lockName = "AuthMongockLock";
    private static final String packageName = "com.agilysys.platform.authservice.migration";

    @Value("${mongodb-dbname:${mongo.db.dbname:}}")
    private String dbName;

    @Bean("mongock-spring-boot")
    public SpringBootMongock mongock(ApplicationContext springContext, MongoClient mongoClient) {
        return new SpringBootMongockBuilder(mongoClient, dbName, packageName)
                .setApplicationContext(springContext)
                .setLockQuickConfig()
                .build();
    }
}
```

PRIORITY
Normal

Steps to Reproduce
Create a Spring Boot 2.1.5 project and try to use Mongock-Spring 2.0.2.

Specific scenario
I have looked at the sample projects provided for Spring-Mongock and they don't seem to solve any of my issues. I have even tried switching to use the stand alone library but that didn't help.

Behaviour
Expected behavior: Application should start and run my existing migration methods.

Actual behavior: Application fails to start.

Reproduces how often: 100%

Version
2.0.2

Link to repository using Mongock
Not possible.

Additional Information
Thanks

**Comment by dieppa** [comment]
Hello @bdchatham , thanks for this long explanation. We will have a look tomorrow during the day as we are in BST time zone. 

Don't worry, you will get it work ;)

**Comment by dieppa** [comment]
which java version are you using?

**Comment by dieppa** [comment]
Hi @bdchatham 
could you do a mvn dependency:tree and provide me, at least, what is under `com.github.cloudyrock.mongock:mongock-spring`, please?

**Comment by bdchatham** [comment]
@dieppa We are using Java 8. 

Here is the dependency tree in our service`[INFO] com.agilysys:auth-service:war:5.0.75-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.1.5.RELEASE:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.19:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.19:compile
[INFO] |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.19:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.1.5.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.1.5.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.5.RELEASE:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.11.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.26:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.23:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.1.5.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.8:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.8:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.8:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.0.16.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.4.0:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.1.7.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.5.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot:jar:2.1.5.RELEASE:compile
[INFO] +- io.dropwizard.metrics:metrics-healthchecks:jar:4.0.5:compile
[INFO] +- com.agilysys.platform:persistence-toolkit:jar:5.0.60-SB2:compile
[INFO] |  +- com.agilysys.platform:common:jar:5.0.60-SB2:compile
[INFO] |  \- org.mongodb:mongo-java-driver:jar:3.8.2:compile
[INFO] +- com.agilysys.platform:rest-toolkit:jar:5.0.60-SB2:compile
[INFO] |  +- com.agilysys.platform:security-common:jar:5.0.60-SB2:compile
[INFO] |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  \- org.apache.cxf:cxf-rt-rs-client:jar:3.1.15:compile
[INFO] +- com.agilysys.platform:monitoring-toolkit:jar:5.0.60-SB2:compile
[INFO] |  +- org.aspectj:aspectjweaver:jar:1.9.4:compile
[INFO] |  +- com.newrelic.agent.java:newrelic-api:jar:4.12.1:compile
[INFO] |  +- org.a3badran.platform:request-logging:jar:1.1.1:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- org.apache.commons:commons-math:jar:2.2:compile
[INFO] |  \- io.dropwizard.metrics:metrics-core:jar:4.0.5:compile
[INFO] +- com.agilysys.platform:crypto-toolkit:jar:5.0.60-SB2:compile
[INFO] +- com.agilysys:auth:jar:5.0.20-SNAPSHOT:compile
[INFO] |  +- com.agilysys:auth-interface:jar:5.0.75-SNAPSHOT:compile
[INFO] |  +- com.agilysys.platform:user-interface:jar:5.0.110:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.1.7.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-core:jar:5.1.5.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:5.1.5.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.1.5.RELEASE:compile
[INFO] +- com.agilysys:platform-internal-libraries:jar:5.0.30-SNAPSHOT:compile
[INFO] |  \- org.springframework.data:spring-data-mongodb:jar:2.1.8.RELEASE:compile
[INFO] |     +- org.springframework:spring-tx:jar:5.1.7.RELEASE:compile
[INFO] |     \- org.springframework.data:spring-data-commons:jar:2.1.8.RELEASE:compile
[INFO] +- io.swagger:swagger-jaxrs:jar:1.5.22:compile
[INFO] |  +- io.swagger:swagger-core:jar:1.5.22:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:compile
[INFO] |  |  \- io.swagger:swagger-models:jar:1.5.22:compile
[INFO] |  +- org.reflections:reflections:jar:0.9.11:compile
[INFO] |  |  \- org.javassist:javassist:jar:3.21.0-GA:compile
[INFO] |  \- com.google.guava:guava:jar:27.0.1-jre:compile
[INFO] |     +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |     +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |     +- org.checkerframework:checker-qual:jar:2.5.2:compile
[INFO] |     +- com.google.errorprone:error_prone_annotations:jar:2.2.0:compile
[INFO] |     +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] +- io.swagger:swagger-annotations:jar:1.5.22:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.8:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.8:compile
[INFO] +- org.springframework:spring-context:jar:5.1.7.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.1.7.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:5.1.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.1.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.1.7.RELEASE:compile
[INFO] +- org.springframework:spring-web:jar:5.1.7.RELEASE:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO] +- net.logstash.logback:logstash-logback-encoder:jar:6.1:compile
[INFO] +- com.agilysys.platform:common:test-jar:tests:5.0.60-SB2:test
[INFO] |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.8:compile
[INFO] |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.8:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.8:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.8:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.10.2:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-jsonSchema:jar:2.9.8:compile
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.8:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO] |  +- com.github.fge:json-schema-validator:jar:2.1.3:compile
[INFO] |  |  +- com.github.fge:json-schema-core:jar:1.1.3:compile
[INFO] |  |  |  +- com.github.fge:jackson-coreutils:jar:1.0:compile
[INFO] |  |  |  |  \- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  |  |  \- org.mozilla:rhino:jar:1.7R4:compile
[INFO] |  |  +- javax.mail:mailapi:jar:1.4.3:compile
[INFO] |  |  \- com.googlecode.libphonenumber:libphonenumber:jar:5.4:compile
[INFO] |  +- io.dropwizard.metrics:metrics-json:jar:4.0.5:compile
[INFO] |  +- com.github.spullara.mustache.java:compiler:jar:0.9.6:compile
[INFO] |  +- log4j:log4j:jar:1.2.17:compile
[INFO] |  \- org.projectlombok:lombok:jar:1.18.8:provided
[INFO] +- pl.pragmatists:JUnitParams:jar:1.1.0:test
[INFO] +- org.springframework:spring-test:jar:5.1.7.RELEASE:test
[INFO] +- org.mockito:mockito-core:jar:2.23.4:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.9.12:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.9.12:test
[INFO] |  \- org.objenesis:objenesis:jar:2.6:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.github.cloudyrock.mongock:mongock-spring:jar:2.0.2:compile
[INFO] |  \- com.github.cloudyrock.mongock:mongock-core:jar:2.0.2:compile
[INFO] |     \- cglib:cglib:jar:3.2.7:compile
[INFO] |        +- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] |        \- org.apache.ant:ant:jar:1.10.1:compile
[INFO] |           \- org.apache.ant:ant-launcher:jar:1.10.1:compile
[INFO] +- com.warrenstrange:googleauth:jar:1.1.2:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] +- org.apache.cxf:cxf-rt-frontend-jaxrs:jar:3.1.15:compile
[INFO] |  +- org.apache.cxf:cxf-core:jar:3.1.15:compile
[INFO] |  |  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
[INFO] |  |  |  \- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.3:compile
[INFO] |  \- org.apache.cxf:cxf-rt-transports-http:jar:3.1.15:compile
[INFO] +- org.assertj:assertj-core:jar:3.11.1:test
[INFO] +- org.slf4j:slf4j-api:jar:1.7.26:compile
[INFO] +- org.codehaus.sonar-plugins.java:sonar-jacoco-listeners:jar:3.2:test
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] \- ch.qos.logback:logback-core:jar:1.2.3:compile`

**Comment by dieppa** [comment]
@bdchatham thanks, that helps ;)

**Comment by dieppa** [comment]
Hi @bdchatham ,

I cannot reproduce the error, but I identified exactly where it is. I am preparing a beta version with a code change which will fix that(plus other stuff), but won't be ready before Monday.

**Comment by bdchatham** [comment]
No problem at all @dieppa. My "reproduction steps" were pretty dreadful - this was largely because I figured it'd likely be difficult to reproduce my exact situation to diagnose possible symptoms but was hoping that you'd be able to see something surface-level that was likely a problem by knowing more about what's under the hood of Mongock. 

Monday totally works for me. Our migration isn't incredibly time-sensitive. I'm excited to see if the fix works! Thanks again.

**Comment by dieppa** [comment]
Hello @bdchatham ,

we have done some major changes internal and in the API. Regarding API we have removed support for DB as it's deprecated, but this shouldn't be an issue for you.

Currently we are having some issues releasing the artifact due to some unpleasant java's idiosyncrasies. 

Meanwhile you can check the version following these steps:
- checkout the mongock project
- move to branch 3.0.0.BETA
- mvn clean install
- change the version in your project and run

You may experience some incompatibilities when building Mongock, but you will easily see how to fix it. Otherwise, please let me know and we'll assist you

**Comment by dieppa** [comment]
@bdchatham  let me know if it works fine with your app?

**Comment by bdchatham** [comment]
@dieppa Hey, sorry I didn't get back to you earlier this morning. I just got to cloning and building it locally. I ran my service pointing to the new version, and unfortunately I am still seeing the same issue :( here is my new dependency tree:

![Screen Shot 2019-07-29 at 12 01 17 PM](https://user-images.githubusercontent.com/8429568/62074933-b2b93a00-b1f8-11e9-98d6-a2b193df3368.png)

**Comment by bdchatham** [comment]
My error is: 
![Screen Shot 2019-07-29 at 12 04 47 PM](https://user-images.githubusercontent.com/8429568/62075148-31ae7280-b1f9-11e9-8a5a-af3c7194a162.png)

**Comment by bdchatham** [comment]
My error is: 
![Screen Shot 2019-07-29 at 12 05 23 PM](https://user-images.githubusercontent.com/8429568/62075166-425ee880-b1f9-11e9-9519-475ae085f0b5.png)

**Comment by dieppa** [comment]
That's simply not possible, that class has been removed. Are you sure you checkout the branch 3.0.0.BETA?? I don't mind the version in pom, I mean the git branch

**Comment by bdchatham** [comment]
Hey @dieppa,

Right, I was noticing the commit message on the open PR (assuming that is correlated to this). Strangely, when I do a git clone of the project (which on the BETA branch) I get the BETA parent pom, but both spring-mongock and mongock-core are 2.0.3-SNAPSHOT. Seems there's something funky going on with maven version bumps. When taking a closer look in the GitHub repo I noticed that the pom files were correctly 3.0.0.BETA in both projects, but when I clone I don't get those versions :/

**Comment by bdchatham** [comment]
Yeah, I just downloaded the zip file instead of cloning and now I think I have all of your updated changes. Let me give this another try!

**Comment by bdchatham** [comment]
@dieppa It worked :) Thank you for all of your help!

**Comment by dieppa** [comment]
Great! Well, that's supposed to be a test version. I need to clean some stuff and prepare the final version. I expect to have a beta version released soon, tomorrow probably. Can you use your local one meanwhile?

**Comment by bdchatham** [comment]
@dieppa Absolutely, I'll just keep an eye out for your next merge. Thanks again!

**Comment by dieppa** [comment]
Hi @bdchatham,
3.0.0.BETA is released. There are some changes, checks and documentation I want to do before releasing a stable version, but I don't expect anything affecting you.

Anyway, let me know if you find anything that can be improved ;)

Thanks!
